### PR TITLE
fix: make AM/PM parser case and space insensitive

### LINKED ISSUE #1179: TimePicker coverts lowercase "pm" to "AM"
When I'm typing `1:30pm` in the TimePicker filed, it changes value to `1:30 AM`. Ideally it should properly parse this string and change it to `1:30 PM` or `13:30`.

I'm using Vaadin 14.1.16 w/ Java 11

### PR DESCRIPTION
**Pull request by vursen**
## Description

The PR fixes a bug of TimePicker where `PM` could be interpreted as `AM` when it was written in lowercase. The fix improves the time parser to make it case and space insensitive.

Fixes #1179

## Type of change

- [x] Bugfix

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs-beta/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

### CODE REVIEW

File: vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/resources/META-INF/resources/frontend/timepickerConnector.js [hunk 1]
```diff
@@ -13,6 +13,48 @@
...
+   * @param {string} amPmString
+   * @return {string | null}
+   */
+  function searchAmPmToken(timeString, amPmString) {
+    if (!amPmString) return null;
+
+    // Turn `amPmString` into a space-insensitive regexp representation.
+    const tokenRegExpString = amPmString.split(/\s*/).map(escapeRegExp).join('\\s*');
+
+    // Create an actual regexp with the enabled case-insensitivity.
```
Comment (sissbruecker) [inline vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/resources/META-INF/resources/frontend/timepickerConnector.js:48]:
```suggestion
    // Create a regexp without case-sensitivity.
```

File: vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/resources/META-INF/resources/frontend/timepickerConnector.js [hunk 2]
```diff
@@ -13,6 +13,48 @@
...
+   * `searchAmPmToken('1 P M', 'PM')` => `'P M'`
+   *
+   * @example
+   * `searchAmPmToken('1 a.m.', 'A. M.')` => `a.m.`
+   *
+   * @param {string} timeString
+   * @param {string} amPmString
+   * @return {string | null}
+   */
+  function searchAmPmToken(timeString, amPmString) {
```
Comment (sissbruecker) [inline vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/resources/META-INF/resources/frontend/timepickerConnector.js:42]:
```suggestion
  function searchAmOrPmToken(timeString, amOrPmString) {
```

**Review by sissbruecker — APPROVED** [review]
