### PR TITLE
fix: grid selection column indeterminate state

### LINKED ISSUE #1060: Grid selection column indeterminate state not shown in Flow component
### Description
The `vaadin-grid` doesn't show selection checkbox in indeterminate state.
Another minor flaw is that the checkbox in header appears to be smaller than checkboxes in column.

### Expected outcome
As seen in web component version
image

### Actual outcome
image

### Live Demo
See multiselect demos in https://vaadin.com/components/vaadin-grid/java-examples/selection

### PR DESCRIPTION
**Pull request by sissbruecker**
## Description

Adds the missing indeterminate state to the Flow grid selection column.

Fixes #1060 

## Type of change

- [x] Bugfix

### CODE REVIEW

File: vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModel.java [hunk 1]
```diff
@@ -437,12 +446,13 @@ private void doUpdateSelection(Map<Object, T> addedItems,
...
         fireSelectionEvent(new MultiSelectionEvent<>(getGrid(),
                 getGrid().asMultiSelect(), oldSelection, userOriginated));
-        if (!removedItems.isEmpty()) {
-            selectionColumn.setSelectAllCheckboxState(false);
-        } else {
-            long size = getDataProviderSize();
-            selectionColumn.setSelectAllCheckboxState(size == selected.size());
-        }
+
+        long size = getDataProviderSize();
```
Comment (sissbruecker) [inline vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModel.java:450]: Same here, the previous optimization of not calling the data provider when at least one item is removed does not suffice anymore when trying to calculate the indeterminate state. When refactoring we could introduce other optimizations instead, for example pass in additional information into this method, whether a select all / deselect triggered this update.

File: vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModel.java [hunk 2]
```diff
@@ -338,7 +345,7 @@ public boolean isSelectionColumnFrozen() {
     protected abstract void fireSelectionEvent(
             SelectionEvent<Grid<T>, T> event);
 
-    private void clientSelectAll() {
+    void clientSelectAll() {
```
Comment (sissbruecker) [inline vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModel.java:348]: Made this package-private in order to be able to test this from unit tests.

File: vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModel.java [hunk 3]
```diff
@@ -395,13 +403,14 @@ private void clientSelectAll() {
                         fetchAllDescendants(child, dataProvider)));
     }
 
-    private void clientDeselectAll() {
+    void clientDeselectAll() {
```
Comment (sissbruecker) [inline vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModel.java:406]: Made this package-private in order to be able to test this from unit tests.

File: vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModel.java [hunk 4]
```diff
@@ -114,17 +114,17 @@ public void selectFromClient(T item) {
...
             if (!isSelectAllCheckboxVisible()) {
                 // Skip changing the state of Select All checkbox if it was
                 // meant to be hidden
                 return;
             }
 
-            size = getDataProviderSize();
-
+            long size = getDataProviderSize();
             selectionColumn.setSelectAllCheckboxState(size == selected.size());
```
Comment (vursen) [inline vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModel.java:124]: It took me a while before I realized that `size === selected.size()` will never be true when a hierarchical data provided is used. This might an argument for adding the `!isHierarchicalDataProvider() &&`  part to this condition to make it more explicit, same as in [`doUpdateSelection`](https://github.com/vaadin/flow-components/pull/2954/files#diff-ccb763b854e892ae3aa6c588f4098769bb35a60db672882ac9dfb852389c6dadR428).

Comment (sissbruecker) [reply vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModel.java]: Yeah, might be easier to comprehend, even though the condition would always fail anyways. Added.

File: vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModelTest.java [hunk 5]
```diff
@@ -299,7 +309,344 @@ public void selectFromClient_lazyUnknownSizeDataProviderWithHidden_skipsUpdateCh
...
+
+        // Deselect all
+        grid.asMultiSelect().updateSelection(Set.of(), Set.of("bar"));
+        Assert.assertFalse((boolean) columnElement.getPropertyRaw("selectAll"));
+        Assert.assertFalse(
+                (boolean) columnElement.getPropertyRaw("indeterminate"));
+    }
+
+    @Test
+    public void hierarchicalDataProvider_select_updatesCheckboxStates() {
```
[the remark this answers is not in the document]
Comment (sissbruecker) [reply vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModelTest.java]: OK, done. I also removed this test: https://github.com/vaadin/flow-components/pull/2954/files#diff-f5e92b595edbe31cde9b82a27fadb63161925f59ea7f56cb54c6134e73234cceL110

It's not really clear what it was supposed to test. If it's just about not throwing exceptions, then that is now covered by the new tests which also call the tested method. As for testing the selected items, we should probably add an actual test suite for that at some point.

**Review by vursen — APPROVED** [review]
