### PR TITLE
fix: preserve setDetailsVisibleOnClick on re-attach

### LINKED ISSUE #1485: Reattaching a grid resets detailsVisibleOnClick
If you set
```java
        grid.setDetailsVisibleOnClick(false);
```
but then detaches and reattaches a grid, the grid behaves as if `detailsVisibleOnClick` is true.

### Example
```java
package com.vaadin.flow.component.grid.it;

import com.vaadin.flow.component.grid.Grid;
import com.vaadin.flow.component.html.Div;
import com.vaadin.flow.component.html.NativeButton;
import com.vaadin.flow.data.renderer.TemplateRenderer;
import com.vaadin.flow.router.Route;

@Route
public class DetailsVisibleOnClickPage extends Div {

    public DetailsVisibleOnClickPage() {
        final Grid<String> grid = new Grid<String>();
        grid.setSelectionMode(Grid.SelectionMode.NONE);
        grid.setItems("AAA", "BBB");
        grid.addColumn(item -> item);
        grid.setItemDetailsRenderer(TemplateRenderer.<String>of(
            "<div class='custom-details' style='border: 1px solid gray; padding: 10px; width: 100%; box-sizing: border-box;'>"
                + "<div>Hi! My name is <b>[[item.item]]!</b></div>" + "</div>")
            .withProperty("item", item -> item));
        grid.setDetailsVisibleOnClick(false);
        add(new NativeButton("Attach grid", e -> add(grid)),
            new NativeButton("Detach grid", e -> remove(grid)), grid);
    }
}
```
### Steps to reproduce
In the example above,
1. Click on a item. Details is not shown.
1. Click on the "Detach grid" button.
1. Click on the "Attach grid" button
1. Click on the item again. This time details is shown.

### PR DESCRIPTION
**Pull request by web-padawan**
## Description

Similarly to #2711, use `getElement().setProperty()` so that Flow would take care of synchronizing the state on reattach.

Fixes #1485

## Type of change

- Bugfix

### CODE REVIEW

File: vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java [hunk 1]
```diff
@@ -3033,8 +3033,7 @@ public void setDetailsVisible(T item, boolean visible) {
     public void setDetailsVisibleOnClick(boolean detailsVisibleOnClick) {
         if (this.detailsVisibleOnClick != detailsVisibleOnClick) {
             this.detailsVisibleOnClick = detailsVisibleOnClick;
```
Comment (tomivirkki) [inline vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java:3035]: The internal `detailsVisibleOnClick` property can assumably be removed also (to avoid double bookkeeping). The `isDetailsVisibleOnClick()` could be modified to read the element property `!getElement().getProperty("__disallowDetailsOnClick", false)`

**Review by tomivirkki — APPROVED** [review]
