### PR TITLE
fix: remove the block that resets tree grid connector and add integration test

### LINKED ISSUE #3434: TreeGrid data provider refresh all with new filter when scrolled down shows empty rows
### Description

There is a bug with TreeGrid and getDataProvider().refreshAll() when scrolled towards the bottom with lazy loading several times.

HierarchicalDataProvider is used for the tree grid's dataprovider. It is filtered within the HierarchicalDataProvider. getDataProvider().refreshAll() is called when someone clicks on a checkbox for filtering.

It works when if it is scrolled near the top, but if it is scrolled near the bottom, utilizing the lazy load several times, it ends up with empty rows when refreshAll() is called with filtered results. It shows the correct number of rows, but they are empty.

### Expected outcome

Expected outcome is to see the same results as grid shows also in TreeGrid however filtered samples are not visible in TreeGrid.

### Minimal reproducible example

In a view, following code can be written to reproduce the bug:

     public static class Person {
        private String firstName;
        private String lastName;

        public Person(String firstName, String lastName) {
            this.firstName = firstName;
            this.lastName = lastName;
        }

        public String getFirstName() {
            return firstName;
        }

        public String getLastName() {
            return lastName;
        }
    }

    boolean showAll = true;
    TextField textField = new TextField("Your name");

    List<Person> people = new ArrayList<>();
    TreeGrid<Person> treeGrid = new TreeGrid<>();

    Grid<Person> grid = new Grid<>();

    public void switchShow() {

        showAll = !showAll;
        treeGrid.getDataProvider().refreshAll();
        grid.getDataProvider().refreshAll();
    }

    public EmptyView() {
        Button button = new Button("Say hello", e -> switchShow());
        button.addThemeVariants(ButtonVariant.LUMO_PRIMARY);
        button.addClickShortcut(Key.ENTER);
        addClassName("centered-content");

        setMaxWidth("80%");
        add(textField, button);

        for (int i = 0; i <500; ++i) {
            people.add(new Person("First" + i, i + "Last"));
        }

        HierarchicalDataProvider<Person, Void> dataProviderTreeGrid =
                new AbstractBackEndHierarchicalDataProvider<Person, Void>() {
                    @Override
                    public int getChildCount(HierarchicalQuery<Person, Void> query) {
                        int pageNum = query.getPage();
                        int pageSize = query.getPageSize();
                        if (showAll) {
                            return people.size();
                        }
                        else {
                            return 5;
                        }
                    }
                    @Override
                    public boolean hasChildren(Person item) {
                        return false;
                    }

                    @Override
                    protected Stream<Person> fetchChildrenFromBackEnd(
                            HierarchicalQuery<Person, Void> query) {
                        int pageNum = query.getPage();
                        int pageSize = query.getPageSize();
                        if (showAll) {
                            int lastIdx = query.getLimit() + query.getOffset();
                            if (lastIdx >= people.size()) {
                                lastIdx = people.size();
                            }
                            return people.subList(query.getOffset(), lastIdx).stream();
                        }
                        else {
                            return people.subList(5, 10).stream();
                        }
                    }
                };

        treeGrid.setDataProvider(dataProviderTreeGrid);
        treeGrid.addColumn(Person::getFirstName).setHeader("First Name").setKey("firstName");
        treeGrid.addColumn(Person::getLastName).setHeader("Last Name").setKey("lastName");
        add(new Label("TreeGrid Example"));
        add(treeGrid);

        grid.setItems(query -> {
                    int pageNum = query.getPage();
                    int pageSize = query.getPageSize();
                    if (showAll) {
                        int startIdx = pageNum * pageSize;
                        int lastIdx = startIdx + pageSize;
                        if (lastIdx >= people.size()) {
                            lastIdx = people.size();
                        }
                        return people.subList(startIdx, lastIdx).stream();
                    }
                    else {
                        return people.subList(5, 10).stream();
                    }
                },
                query -> {
                    int pageNum = query.getPage();
                    int pageSize = query.getPageSize();
                    if (showAll) {
                        return people.size();
                    }
                    else {
                        return 5;
                    }
                }
        );

        grid.addColumn(Person::getFirstName).setHeader("First Name").setKey("firstName");
        grid.addColumn(Person::getLastName).setHeader("Last Name").setKey("lastName");
        add(new Label(""));
        add(new Label("Grid Example"));
        add(grid);

### Steps to reproduce

When the example code runs,
There will be two grids visible: TreeGrid and normal Grid
1. Scroll towards the bottom at least for 200 samples or above
2. Click the button for filtering
3. Observe if the behavior the same or not for the grids

### Environment

Vaadin version(s): 21.0.2
OS: MacOS
Also replicated this with Vaadin 23.1.2

### Browsers

Chrome

### PR DESCRIPTION
**Pull request by ugur-vaadin**
## Description

When using a TreeGrid with lazy loading and the grid was scrolled beyond the 100th item, if the child count is set to less than the upper limit of the latest query and `getDataProvider().refreshAll()` is called, the grid showed incorrect results.

This pull request removes the block that resets TreeGrid connector, which caused some requests to be lost. An integration test was also added in order to prevent the issue from being introduced again.

Fixes #3434

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs-beta/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

### CODE REVIEW

File: vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/treegrid/it/LazyLoadingTreeGridRefreshAllPage.java [hunk 1]
```diff
@@ -0,0 +1,79 @@
...
+import com.vaadin.flow.function.ValueProvider;
+import com.vaadin.flow.router.Route;
+
+import java.util.stream.IntStream;
+import java.util.stream.Stream;
+
+@Route("vaadin-grid/lazy-loading-treegrid-refreshall")
+public class LazyLoadingTreeGridRefreshAllPage extends Div {
+
+    private TreeGrid<HierarchicalTestBean> treeGrid = new TreeGrid<>();
```
Comment (yuriy-fix) [inline vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/treegrid/it/LazyLoadingTreeGridRefreshAllPage.java:34]:
```suggestion
    private TreeGrid<String> treeGrid = new TreeGrid<>();
```

File: vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/treegrid/it/LazyLoadingTreeGridRefreshAllPage.java [hunk 2]
```diff
@@ -0,0 +1,79 @@
...
+        childCount.setValue(500);
+        refreshAll.setId("refresh-all");
+        add(childCount, refreshAll);
+
+        treeGrid.setDataProvider(new LazyLoadingProvider());
+        treeGrid.addHierarchyColumn(ValueProvider.identity()).setHeader("Name");
+        add(treeGrid);
+    }
+
+    private class LazyLoadingProvider<String, Void>
```
Comment (yuriy-fix) [inline vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/treegrid/it/LazyLoadingTreeGridRefreshAllPage.java:52]:
```suggestion
    private class LazyLoadingProvider
```

File: vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/treegrid/it/LazyLoadingTreeGridRefreshAllPage.java [hunk 3]
```diff
@@ -0,0 +1,79 @@
...
+        public int getChildCount(HierarchicalQuery<String, Void> query) {
+            return childCount.getValue();
+        }
+
+        @Override
+        public Stream<String> fetchChildren(
+                HierarchicalQuery<String, Void> query) {
+            int limit = query.getLimit();
+            int offset = query.getOffset();
+            return (Stream<String>) IntStream.range(offset, offset + limit)
```
Comment (yuriy-fix) [inline vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/treegrid/it/LazyLoadingTreeGridRefreshAllPage.java:65]:
```suggestion
            return IntStream.range(offset, offset + limit)
```

**Review by yuriy-fix — APPROVED** [review]

**Comment by yuriy-fix** [comment]
Please run formatter before merging.
