### PR TITLE
fix: ensure deselectAllowed is preserved on re-attach

### LINKED ISSUE #2696: Reattaching grid ignores setDeselectAllowed(false)
### Description
Setting `GridSingleSelectionModel#setDeselectAllowed(false)` doesn't work after grid is reattached. The grid seems to ignore that `setDeselectAllowed` is false and behaves as if it is true after reattachment.

### Expected outcome

`setDeselectAllowed(false)` should still prevent deselection after grid is reattached.   

### Actual outcome

`setDeselectAllowed(false)` allows deselection after grid is reattached.   

### Live Demo 

deselection

### Minimal reproducible example

```
private Grid<String> grid = new Grid<>();

public DeselectNotAllowedView() {

    grid.setSelectionMode(SelectionMode.SINGLE);
    GridSingleSelectionModel<String> singleSelect =
        (GridSingleSelectionModel<String>) grid.getSelectionModel();
    singleSelect.setDeselectAllowed(false);
    
    add(new Button("Attach", e -> add(grid)));
    add(new Button("Detach", e -> remove(grid)));
    
    grid.setItems("A", "B", "C");
    grid.addColumn(x -> x).setHeader("Col");
    grid.select("A");

    add(grid);
}
```

### Steps to reproduce

1. Create a project with the attached example.
2. Click on selected item and see deselection not happening.
2. Click "detach" button to remove the grid.
3. Click "attach" button to reattach the grid.
4. Click on selected item and see deselection happening.

### Environment

- Vaadin version 22.0.5.

### Browsers Affected
- [X] Chrome
- [X] Firefox

### PR DESCRIPTION
**Pull request by web-padawan**
## Description

Added the logic to update `deselectAllowed` on the connector when grid is attached.

Fixes #2696

## Type of change

- Bugfix

### CODE REVIEW

File: vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java [hunk 1]
```diff
@@ -269,9 +269,7 @@ protected void fireSelectionEvent(
                     @Override
                     public void setDeselectAllowed(boolean deselectAllowed) {
                         super.setDeselectAllowed(deselectAllowed);
-                        grid.getElement().executeJs(
-                                "this.$connector.deselectAllowed = $0",
-                                deselectAllowed);
+                        grid.updateDeselectAllowed(deselectAllowed);
```
Comment (tomivirkki) [inline vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java:272]: You could probably use `grid.getElement().setProperty('deselectAllowed', deselectAllowed)` and and then make the `gridConnector` read `grid.deselectAllowed` instead of `grid.$connector.deselectAllowed`. Then Flow will take case of synchronizing the state on attach.

Comment (web-padawan) [reply vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java]: Thanks, seems to work. Done.

File: vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js [hunk 2]
```diff
@@ -209,7 +209,7 @@ import { isFocusable } from '@vaadin/grid/src/vaadin-grid-active-item-mixin.js';
         }
         if (!newVal) {
           if (oldVal && selectedKeys[oldVal.key]) {
-            if (!grid.$connector.deselectAllowed) {
+            if (!grid.__deselectAllowed) {
```
Comment (tomivirkki) [inline vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js:212]: There is also a line that sets `grid.$connector.deselectAllowed = true;`. That can be removed now.

File: vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java [hunk 3]
```diff
@@ -1378,6 +1376,8 @@ public Grid(Class<T> beanType) {
         addDragEndListener(this::onDragEnd);
 
         getElement().setAttribute("suppress-template-warning", true);
+
+        getElement().setProperty("__deselectAllowed", true);
```
Comment (tomivirkki) [inline vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java:1380]: Should we rename the property to `__deselectDisallowed` so we wouldn't need to set a truthy default value for it?

File: vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js (hunk 2 above)
Comment (web-padawan) [reply vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js]: Done.

File: vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java (hunk 3 above)
Comment (web-padawan) [reply vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java]: Done.

**Review by tomivirkki — APPROVED** [review]
