### PR TITLE
fix: prevent debouncer override in callback

### LINKED ISSUE #3595: ComboBox Error = Problem with another choosing after first choosing (with items from stream and addValueChangeListener)
### Description

We (me and my coworker)  find a problem using Vaadin ComboBox component with stream (in my example) or dataproviding methods for items loading to ComboBox and with addValueChangeListner method.
I create an easy example project with such ComboBox field based on MyTodo project from Vaadin site GetStarted.

### Expected outcome

Choosing from ComboBox should be enabled.

### Minimal reproducible example

[VaadinComboBoxErrorExample.zip](https://github.com/vaadin/flow-components/files/9337045/VaadinComboBoxErrorExample.zip)

### Steps to reproduce

1. Open Project for example under IntelliJ.
2. Run Project -> Automatic Open Browser Page with ComboBox to choose a town from list.
3. Write "Warszawa" into combobox.
4. Choose "Warszawa" town from the opened combobox list.
5. Click outside the combobox - for example on empty side space.
6. Click inside the combobox after word "Warszawa". At this moment Combobox open a Combbox list with one element "Warszawa..." to choose an alement but the element is disabled and blue circle is still running.

### Environment

Vaadin version(s):  23.1.6
OS: Windows 11
Java 17
IntelliJ

### Browsers

Chrome

### PR DESCRIPTION
**Pull request by ugur-vaadin**
## Description

There was a single debouncer, and 2 ways to set it in the connector. In some cases, the debouncer is overridden by the other, which results in callbacks that are never completed and never cleared. Therefore, the loading state is never resolved.

This PR prevents the debouncer override. The data request is now performed without the debouncer. While the debouncer is active, the callbacks that do not contain filter changes are not executed right away, but within the debouncer. 

Fixes #3595 

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs-beta/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

### CODE REVIEW

File: vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/resources/META-INF/resources/frontend/comboBoxConnector.js [hunk 1]
```diff
@@ -70,6 +71,13 @@ import { ComboBoxPlaceholder } from '@vaadin/combo-box/src/vaadin-combo-box-plac
         };
 
         comboBox.dataProvider = function (params, callback) {
+          const filterUnchanged = params.filter === lastFilter;
+          if (filterUnchanged && this._debouncer) {
+            if (pageInDebouncer !== params.page) {
+              pageCallbacks[params.page] = callback;
+            }
+            return;
+          }
```
Comment (vursen) [inline vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/resources/META-INF/resources/frontend/comboBoxConnector.js:80]: I'm wondering if it is necessary to store and check `pageInDebouncer`. The page that was requested first with the new filter can't be re-requested because it is already in the web component's `_pendingRequests`, I think. So, I wonder if we could just do something like that:

```js
if (filterChanged) {
  cache = {};
  lastFilter = params.filter;
  ...
}

if (this._filterDebouncer) {
  pageCallbacks[params.page] = callback;
  return;
}
```

Comment (ugur-vaadin) [reply vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/resources/META-INF/resources/frontend/comboBoxConnector.js]: Addressed in new commit

File: vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/LazyLoadingPage.java [hunk 2]
```diff
@@ -278,7 +280,7 @@ private void createComboBoxWithCustomPageSizeAndLazyLoading() {
     }
 
     private void createComboBoxWithDisabledLazyLoading() {
-        addTitle("ComboBox with disabled lazy loading");
+        addTitle("");
```
Comment (vursen) [inline vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/LazyLoadingPage.java:283]: Looks like an unintentional change.

File: vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/LazyLoadingIT.java [hunk 3]
```diff
@@ -62,6 +63,8 @@ public void init() {
                 By.id("callback-dataprovider-size-request-count"));
         disabledLazyLoadingBox = $(ComboBoxElement.class)
                 .id("disabled-lazy-loading");
+        lazyWithSmallCustomPageSize = $(ComboBoxElement.class)
```
Comment (vursen) [inline vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/LazyLoadingIT.java:66]:
```suggestion
        lazyWithSmallPageSize = $(ComboBoxElement.class)
```

File: vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/LazyLoadingIT.java [hunk 4]
```diff
@@ -62,6 +63,8 @@ public void init() {
...
+                .id("lazy-small-page-size");
```
Comment (vursen) [inline vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/LazyLoadingIT.java:67]:
```suggestion
                .id("lazy-small-custom-page-size");
```

File: vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/LazyLoadingIT.java [hunk 5]
```diff
@@ -576,6 +579,24 @@ public void disabledLazyLoading_reducePageSize_enablesLazyLoading() {
         assertRendered("99");
     }
 
+    @Test
+    // https://github.com/vaadin/flow-components/issues/3595
+    public void customPageSize_filter_selectItem_loadingStateResolved() {
```
Comment (vursen) [inline vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/LazyLoadingIT.java:584]:
```suggestion
    public void smallCustomPageSize_filter_selectItem_loadingStateResolved() {
```

**Review by vursen — APPROVED** [review]
