### PR TITLE
fix: listen to file-reject instead of file-rejected

### LINKED ISSUE #4695: FileRejectedListener event does not fire in Vaadin 24.0.0.beta2
### Description

In the example on the https://vaadin.com/docs/latest/components/upload#file-format page, the event fires

The same example aud the page https://vaadin.com/docs/next/components/upload#file-format is broken

### Expected outcome

The event does not fire

### Minimal reproducible example

https://vaadin.com/docs/next/components/upload#file-format

### Steps to reproduce

Tested on the web page

### Environment

Vaadin version(s): 
OS: 24.0.0.beta2

### Browsers

_No response_

### PR DESCRIPTION
**Pull request by ugur-vaadin**
## Description

The name of the event contained a typo, which lead to event not being caught. This PR fixes the typo and adds a file rejection test.

Fixes #4695 

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/contributing/overview
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

### CODE REVIEW

File: vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/test/java/com/vaadin/flow/component/upload/tests/AbstractUploadIT.java [hunk 1]
```diff
@@ -9,11 +9,25 @@
 
 public abstract class AbstractUploadIT extends AbstractComponentIT {
     /**
+     * Creates a temp file with ".txt" extension for testing purposes.
+     *
      * @return The generated temp file handle
      * @throws IOException
      */
     File createTempFile() throws IOException {
```
Comment (vursen) [inline vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/test/java/com/vaadin/flow/component/upload/tests/AbstractUploadIT.java:17]: I would suggest that we always require tests to specify the extension when creating temp files. That will be more explicit. In other words, I suggest only leaving `createTempFile(String extension)`.

Comment (ugur-vaadin) [reply vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/test/java/com/vaadin/flow/component/upload/tests/AbstractUploadIT.java]: That makes sense, considering extension is important for file upload. Updated the PR.

**Review by vursen — APPROVED** [review]

**Review by bwajtr — APPROVED** [review]
