### PR TITLE
fix: call `numberFormatter` from point object

### LINKED ISSUE #8487: [spreadsheet] `Highcharts is not defined` error thrown on client
### Description

In some cases, charts inside a sheet can throw an error in the browser when the user hover over data points. This happens when the data source for the chart contains cells formatted with a format other than "General" and the decimal count is greater than 0. 

The source of this issue is this line in the `ChartDataToVaadinConfigWriter` class:

https://github.com/vaadin/flow-components/blob/1658cce3fe328abdd6f2a54a341b216f1a4ea25f/vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/java/com/vaadin/flow/component/spreadsheet/charts/converter/confwriter/ChartDataToVaadinConfigWriter.java#L140

`Highcharts` is not globally available in the `window` scope, since it is imported within a JS module scope. The series formatter logic was [taken from the Spreadsheet for FW8](https://github.com/vaadin/spreadsheet/blob/24208dd845a50bd467ae87ab2e1db640795f08bb/vaadin-spreadsheet-charts/src/main/java/com/vaadin/addon/spreadsheet/charts/converter/confwriter/ChartDataToVaadinConfigWriter.java#L132-L147), where `Highcharts` was imported differently.

### Steps to reproduce

1. Run Spreadsheet IT module with `mvn jetty:run`
2. Load this example file: [test.xlsx](https://github.com/user-attachments/files/24639012/test.xlsx)
3. Open the browser's console
4. Hover over the data points

### PR DESCRIPTION
**Pull request by DiegoCardoso**
## Description

Replace a call to `Highcharts.numberFormat` with a call to the `numberFormatter` method present in the charts object. The previous code assumed that the `Highcharts` object was globally available to work, which is not the case anymore.

Fixes #8487

## Type of change

- Bugfix

### CODE REVIEW

File: vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/java/com/vaadin/flow/component/spreadsheet/charts/converter/confwriter/ChartDataToVaadinConfigWriter.java [hunk 1]
```diff
@@ -127,21 +127,24 @@ private void updateTooltip(ChartData definition, Configuration conf) {
...
+                       var formattedNumber;
+                       var signlessNumer = Math.abs(this.$v);
+                       if ($tooltipDecimals < 0 ) {
+                          //Round numbers to contain only 9 digits if they contain decimals.
+                          var tooltipDecimals = (signlessNumer>1.0 ? 9-Math.floor(Math.log(signlessNumer)/Math.LN10) : 9);
+                          formattedNumber = (Math.round(this.$v) == this.$v ? this.$v : Math.round(this.$v * Math.pow(10,tooltipDecimals))/Math.pow(10,tooltipDecimals));
+                       } else {
+                          //numberFormat can handle numbers 20 digits long.
+                          var tooltipDecimals = (Math.ceil(Math.log(signlessNumer)/Math.LN10) + $tooltipDecimals<= 20 ? $tooltipDecimals : 20);
+                          formattedNumber = this.point.series.chart.numberFormatter(this.$v, tooltipDecimals);
```
Comment (DiegoCardoso) [inline vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/java/com/vaadin/flow/component/spreadsheet/charts/converter/confwriter/ChartDataToVaadinConfigWriter.java:141]: This is the relevant change to fix the issue. I changed this session to a text block to make SonaQube happy, but I can do it in a separate PR.
