### PR TITLE
fix: disable client-side validation for CheckboxGroup

### LINKED ISSUE #2823: Validation message in CheckboxGroup does not appear directly on invalid selection and disappears when focusing out
### Description

Similar to the issue https://github.com/vaadin/vaadin-radio-button/issues/179 that affected RadioButtonGroups, the validation message for CheckboxGroups disappears when focusing out of the component. It also does not appear directly when an invalid selection is preselected after adding a Binder.

### Expected outcome

What did you expect to happen?

The validation message should appear directly if an invalid selection is done. It also should stay on-screen when changing focus from the CheckboxGroup. 

### Actual outcome

The validation message does not appear directly below a CheckboxGroup when an invalid selection is preset. It also disappears when focusing out of the CheckboxGroup.

### Minimal reproducible example

This is a sample code for the checkbox group.
```java
CheckboxGroup<String> cbg = new CheckboxGroup<>();
cbg.setItems("valid 1", "valid 2", "invalid");

Binder<AtomicReference<Set<String>>> cbgBinder = new Binder<>();
cbgBinder.forField(cbg)
		.withValidator(values -> !values.contains("invalid"), "This selection is invalid!")
		.bind(AtomicReference::get, AtomicReference::set);

cbg.select("invalid");

this.add(cbg, new TextField());
```

The following is a sample reference code for the behaviour of a RadioButtonGroup, which behaves differently:
```java
RadioButtonGroup<String> rbg = new RadioButtonGroup<>();
rbg.setItems("valid 1", "valid 2", "invalid");

Binder<AtomicReference<String>> rbgBinder = new Binder<>();
rbgBinder.forField(rbg)
		.withValidator(value -> !"invalid".equals(value), "Value is invalid")
		.bind(AtomicReference::get, AtomicReference::set);

rbg.setValue("invalid");

this.add(rbg, new TextField());
```

### Steps to reproduce

1. Create a CheckboxGroup and set items .
2. Add a binder that displays an error message when the invalid selection is selected.
3. Programmatically set an invalid selection
4. Change focus to the textfield, e.g. by clicking on it or by tabbing out.

### Environment

- vaadin-checkbox-flow (14.8.1) / Vaadin Flow 14.8.1
- Windows 10

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] Safari (not tested)
- [x] Edge
- [ ] IE 11 (not tested)
- [ ] iOS Safari (not tested)
- [ ] Android Chrome (not tested)

### PR DESCRIPTION
**Pull request by sissbruecker**
## Description

Disables client-side validation for the CheckboxGroup component, by overriding the client-side validation function and removing synchronization of the `invalid` property. The solution is adapted from a similar fix for RadioButtonGroup (https://github.com/vaadin/flow-components/pull/461). Note that the fix in RadioButtonGroup has changed quite a bit over time.

Fixes #2823 

## Type of change

- [x] Bugfix

### CODE REVIEW

File: vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/src/test/java/com/vaadin/flow/component/checkbox/tests/CheckboxGroupIT.java [hunk 1]
```diff
@@ -191,9 +191,6 @@ public void groupHasLabelAndErrorMessage_setInvalidShowEM_setValueRemoveEM() {
                 "Correct error message should be shown after the button clicks",
                 "Field has been set to invalid from server side",
                 errorMessage.getText());
-
-        executeScript("arguments[0].value=['2'];", group);
-        verifyGroupValid(group, errorMessage);
```
Comment (sissbruecker) [inline vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/src/test/java/com/vaadin/flow/component/checkbox/tests/CheckboxGroupIT.java:196]: This test had the wrong assumption that setting a value on the client should make the component valid. That's not correct, as long as the component has been set to invalid, it should stay invalid.

File: vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/FieldValidationUtil.java [hunk 2]
```diff
@@ -0,0 +1,54 @@
...
+                    "Component %s is not attached. Client side validation "
+                            + "should be disabled when the component is "
+                            + "attached, thus this method needs to be called "
+                            + "from the onAttach method of the component.",
+                    component));
+        }
+        // Wait until the response is being written as the validation state
+        // should not change after that
+        component.getUI().ifPresent(ui -> ui.beforeClientResponse(component,
+                executionContext -> overrideClientValidation(component)));
```
Comment (vursen) [inline vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/FieldValidationUtil.java:36]: Looking at other similar places where the client-side validation is getting disabled for other components, it seems that they do it slightly differently:

```java
final StateNode componentNode = component.getElement().getNode();
componentNode.runWhenAttached(ui -> ui.getInternals().getStateTree()
        .beforeClientResponse(componentNode,
                executionContext -> overrideClientValidation(
                        component)));
```

Just want to make sure if there is any significant difference.

Comment (sissbruecker) [reply vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/FieldValidationUtil.java:36]: Right, I simplified that bit, because the `runWhenAttached` wasn't necessary, as the assertion above checks that the component is already attached. Apart from that accessing the `StateNode` is not necessary, and neither is accessing the internal state tree to use `beforeClientResponse`.

Comment (vursen) [reply vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/FieldValidationUtil.java:36]: OK 👍 It would be good to simplify that in other components at some point as well.

**Comment by vursen** [comment]
I quickly looked around and noticed that ComboBox and CustomField might potentionally have the same problem as CheckboxGroup: both don't disable the client-side validation. I'm not sure if CustomField requires the fix right away as I heard it has some fundamental problems with the validation (?). However, as for ComboBox, it is probably worth fixing on a par with CheckboxGroup. 

What do you think?

**Comment by vursen** [comment]
Ok, seems that ComboBox maintains its own way of disabling the client-side validation through the connector:

https://github.com/vaadin/flow-components/blob/b89541a6cec9ce8c0ebdb2e02a919debfcf3b514/vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/resources/META-INF/resources/frontend/comboBoxConnector.js#L272-L287

**Review by vursen — APPROVED** [review]
