### PR TITLE
fix: sync presentation value on data change

### LINKED ISSUE #8882: CheckBoxGroup and RadioButtonGroup do not obey SelectionPreservationMode correctly
### Description

It looks like the thing is completely broken. When using SelectionPreservationMode.PRESERVE_EXISTING, the RadioButtonGroup should retain its value, and if CheckBoxGroup has more than one box selected, it should retain all the selected boxes. Only such selections should be cleared which do not have representative in the data provider anymore. I.e. if you deleted selected item, it will be cleared. Now I see RadioButtonGroup fully cleared and CheckBoxGroup retains only the last selected item. Both are wrong.

### Expected outcome

RadioButtonGroup and CheckBoxGroup to retain its selection when SelectionPreservationMode.PRESERVE_EXISTING or SelectionPreservationMode.PRESERVE_ALL is used with the provided code.

### Minimal reproducible example

```
@Route(value = "selection-preservation", layout = MainLayout.class)
public class SelectionPreservationView extends VerticalLayout {

    public SelectionPreservationView() {
        RadioButtonGroup<Bean> buttonGroup = new RadioButtonGroup<>(
                "Test-radios");
        ListDataProvider<Bean> radioDataProvider = DataProvider.ofCollection(
                IntStream.range(0, 10).mapToObj(i -> new Bean(i)).toList());
        RadioButtonGroupListDataView<Bean> radioDataView = buttonGroup
                .setItems(radioDataProvider);
        buttonGroup.setItemLabelGenerator(b -> "" + b.getValue());

        CheckboxGroup<Bean> checkboxGroup = new CheckboxGroup<>(
                "Test-checkbox");
        ListDataProvider<Bean> checkboxDataProvider = DataProvider.ofCollection(
                IntStream.range(0, 10).mapToObj(i -> new Bean(i)).toList());
        CheckboxGroupListDataView<Bean> checkboxDataView = checkboxGroup
                .setItems(checkboxDataProvider);
        checkboxGroup.setItemLabelGenerator(b -> "" + b.getValue());

        Button btn1 = new Button("Refresh data view", e -> {
            radioDataView.refreshAll();
            checkboxDataView.refreshAll();
        });

        Button btn2 = new Button("Refresh data provider", e -> {
            radioDataProvider.refreshAll();
            checkboxDataProvider.refreshAll();
        });

        var select = new Select<SelectionPreservationMode>();
        select.setLabel("Select mode");
        select.setItems(SelectionPreservationMode.values());
        select.addValueChangeListener(e -> {
            buttonGroup.setSelectionPreservationMode(e.getValue());
            checkboxGroup.setSelectionPreservationMode(e.getValue());
        });
        select.setValue(SelectionPreservationMode.PRESERVE_EXISTING);

        this.add(buttonGroup, checkboxGroup, btn1, btn2, select);
    }

    public static class Bean {
        private int value;

        public Bean(int value) {
            this.value = value;
        }

        public int getValue() {
            return value;
        }

        public void setValue(int value) {
            this.value = value;
        }

        @Override
        public int hashCode() {
            return Objects.hash(value);
        }

        @Override
        public boolean equals(Object obj) {
            if (this == obj)
                return true;
            if (obj == null)
                return false;
            if (getClass() != obj.getClass())
                return false;
            Bean other = (Bean) obj;
            return value == other.value;
        }
    }

}

```

### Steps to reproduce

Use the code example. Select a value in both fields, select multiple items in `CheckBoxGroup`. Then click either of the buttons to trigger `refreshAll`. Use select field to change the mode to observe behavior in different modes.

### Environment

Vaadin version(s): 24.9.12

### Browsers

Issue is not browser related

### PR DESCRIPTION
**Pull request by ugur-vaadin**
## Description

This PR:

- synchronizes the presentation value on data change in order to correctly display the server value on the client side
- adds integration tests in order to prevent regressions

Fixes #8882

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/contributing/overview
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

### CODE REVIEW

File: vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/src/test/java/com/vaadin/flow/component/checkbox/tests/SelectionPreservationIT.java [hunk 1]
```diff
@@ -0,0 +1,111 @@
...
+
+        group.selectByText("1");
+        group.selectByText("3");
+
+        clickElementWithJs("refresh-all");
+
+        Assert.assertTrue(group.getSelectedTexts().isEmpty());
+    }
+
+    private String getServerValue() {
```
Comment (sissbruecker) [inline vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/src/test/java/com/vaadin/flow/component/checkbox/tests/SelectionPreservationIT.java:106]: Nit: This could click `show-server-value` instead of doing that separately in each test. Same for the other components.

Comment (ugur-vaadin) [reply vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/src/test/java/com/vaadin/flow/component/checkbox/tests/SelectionPreservationIT.java:106]: Done.
