### PR TITLE
fix: use correct generic type in ClickNotifier

### LINKED ISSUE #5395: Icon used as the generic type for ClickNotifier in AbstractIcon
### Description

`Icon` is used as the generic type for `ClickNotifier` in `AbstractIcon`. See https://github.com/vaadin/flow-components/blob/dcc122e833a5cac7a73cc967aaa263e0b0dfe500/vaadin-icons-flow-parent/vaadin-icons-flow/src/main/java/com/vaadin/flow/component/icon/AbstractIcon.java#L38

### PR DESCRIPTION
**Pull request by DiegoCardoso**
## Description

Use the correct type in the `ClickNotifier` generic param.

Fixes #5395 

## Type of change

- [X] Bugfix
- [ ] Feature

### CODE REVIEW

File: vaadin-icons-flow-parent/vaadin-icons-flow/src/main/java/com/vaadin/flow/component/icon/AbstractIcon.java [hunk 1]
```diff
@@ -35,7 +35,7 @@
 @NpmPackage(value = "@vaadin/icon", version = "24.2.0-alpha11")
 @JsModule("@vaadin/icon/src/vaadin-icon.js")
 public abstract class AbstractIcon extends Component
-        implements ClickNotifier<Icon>, HasTooltip {
+        implements ClickNotifier<AbstractIcon>, HasTooltip {
```
Comment (tomivirkki) [inline vaadin-icons-flow-parent/vaadin-icons-flow/src/main/java/com/vaadin/flow/component/icon/AbstractIcon.java:38]: Screenshot 2023-08-29 at 14 25 39

I think the `getSource()` should not return `AbstractIcon`, but in this case, it should be an `Icon`.

File: vaadin-icons-flow-parent/vaadin-icons-flow/src/main/java/com/vaadin/flow/component/icon/AbstractIcon.java
Comment (tomivirkki) [inline vaadin-icons-flow-parent/vaadin-icons-flow/src/main/java/com/vaadin/flow/component/icon/AbstractIcon.java:1]: Please also remove the unused import from this class.

File: vaadin-icons-flow-parent/vaadin-icons-flow/src/main/java/com/vaadin/flow/component/icon/AbstractIcon.java (hunk 1 above)
Comment (knoobie) [reply vaadin-icons-flow-parent/vaadin-icons-flow/src/main/java/com/vaadin/flow/component/icon/AbstractIcon.java:38]: Should AbstractIcon be changed to `AbstractIcon<T extends AbstractIcon<T>>` allowing to pass the proper generic to the ClickNotifier?

Comment (DiegoCardoso) [reply vaadin-icons-flow-parent/vaadin-icons-flow/src/main/java/com/vaadin/flow/component/icon/AbstractIcon.java]: I added a generic type to `AbstractIcon` to pass it to `ClickNotifier`, and had to change the implementation in `Icon`  to pass itself as the param type.

**Review by tomivirkki — APPROVED** [review]
