### PR TITLE
fix: remove previous component on slot in add to primary/secondary

### LINKED ISSUE #3586: SplitLayout: Removing and adding a new Component to the Secondary breaks EventListeners in Primary
### Description

If I remove the secondary component from the SplitLayout and add a new component the EventListeners in Primary stop working.

### Expected outcome

Removing and adding should not break anything.

### Minimal reproducible example

```
@PageTitle("Split")
@Route(value = "split", layout = MainLayout.class)
public class SplitView extends SplitLayout {

    public SplitView() {
        Grid<String> grid = new Grid<>();

        grid.addColumn(s -> s);
        grid.addComponentColumn(s -> new Button(s, event -> {
            Notification.show("Hello from " + s);
            if (s.equals("C")) {
                remove(getSecondaryComponent());
                addToSecondary(new Span("New Right"));
            }
        }));

        grid.setItems(List.of("A", "B", "C"));

        addToPrimary(grid);
        addToSecondary(new Span("Right"));
    }
}
```

### Steps to reproduce

After clicking the Button on Row C the EventListener of the Button is no longer called

### Environment

Vaadin version(s): 23.1.3
OS: any

### Browsers

Issue is not browser related

### PR DESCRIPTION
**Pull request by DiegoCardoso**
## Description

Change the SplitLayout behavior to remove only the previous component in the same slot when a new component is added to the primary or secondary slots.

SplitLayout currently removes all children first before adding the components to their slots. This might be unexpected when adding a component to the secondary slot leads to detaching the primary component.

Fixes #3586

## Type of change

- [x] Bugfix
- [ ] Feature

### CODE REVIEW

File: vaadin-split-layout-flow-parent/vaadin-split-layout-flow/src/main/java/com/vaadin/flow/component/splitlayout/SplitLayout.java [hunk 1]
```diff
@@ -325,15 +325,6 @@ public void remove(Component... components) {
         }
     }
 
-    /**
-     * Removes the primary and the secondary components.
-     */
-    public void removeAll() {
```
Comment (knoobie) [inline vaadin-split-layout-flow-parent/vaadin-split-layout-flow/src/main/java/com/vaadin/flow/component/splitlayout/SplitLayout.java:331]: Removing this is a breaking change :)

File: vaadin-split-layout-flow-parent/vaadin-split-layout-flow/src/main/java/com/vaadin/flow/component/splitlayout/SplitLayout.java [hunk 2]
```diff
@@ -294,17 +282,30 @@ public void setSecondaryStyle(String styleName, String value) {
...
+     * @return the component or a wrapper div
+     */
+    private Component getComponentOrWrap(Component... components) {
+        if (components.length == 1) {
+            return components[0];
+        } else {
+            Div container = new Div();
+            container.add(components);
+            return container;
+        }
```
Comment (tomivirkki) [inline vaadin-split-layout-flow-parent/vaadin-split-layout-flow/src/main/java/com/vaadin/flow/component/splitlayout/SplitLayout.java:300]: nit: could be shortened to `return components.length == 1 ? components[0] : new Div(components);`

File: vaadin-split-layout-flow-parent/vaadin-split-layout-flow/src/main/java/com/vaadin/flow/component/splitlayout/SplitLayout.java [hunk 3]
```diff
@@ -294,17 +282,30 @@ public void setSecondaryStyle(String styleName, String value) {
...
+    }
+
     private void setComponent(Component component, String slot) {
         Component child = component == null ? new Div() : component;
+        SlotUtils.clearSlot(this, slot);
         SlotUtils.addToSlot(this, slot, child);
```
Comment (tomivirkki) [inline vaadin-split-layout-flow-parent/vaadin-split-layout-flow/src/main/java/com/vaadin/flow/component/splitlayout/SplitLayout.java:306]: nit: could be shortened to `SlotUtils.setSlot(this, slot, child);`

**Review by tomivirkki — APPROVED** [review]

File: vaadin-split-layout-flow-parent/vaadin-split-layout-flow/src/main/java/com/vaadin/flow/component/splitlayout/SplitLayout.java (hunk 3 above)
Comment (DiegoCardoso) [reply vaadin-split-layout-flow-parent/vaadin-split-layout-flow/src/main/java/com/vaadin/flow/component/splitlayout/SplitLayout.java]: Thanks! Done.

File: vaadin-split-layout-flow-parent/vaadin-split-layout-flow/src/main/java/com/vaadin/flow/component/splitlayout/SplitLayout.java (hunk 2 above)
Comment (DiegoCardoso) [reply vaadin-split-layout-flow-parent/vaadin-split-layout-flow/src/main/java/com/vaadin/flow/component/splitlayout/SplitLayout.java]: Done.
