### PR TITLE
fix: clean confirm dialog slots before adding new content

### LINKED ISSUE #2710: [confirm-dialog] Setting custom buttons keeps adding them instead of replacing them
### Description

Calling a method such as `setConfirmButton` multiple times will keep adding the elements to the slot, instead of replacing them. Only the first call for setting the custom button replaces the default button, after that the Flow component keeps adding content to the slot without removing previous custom content. This problem applies to all button slots (confirm, cancel, reject).

Possible workaround: Keep track of and manually remove previously added buttons.

### Expected outcome

Calling a method such as `setConfirmButton` multiple times results in one button in that slot.

### Actual outcome

Calling a method such as `setConfirmButton` multiple times results in multiple button in that slot.

### Minimal reproducible example

```java
        ConfirmDialog dialog = new ConfirmDialog();
        dialog.setConfirmButton(new Button("Publish Document A"));
        dialog.setConfirmButton(new Button("Publish Document B"));
```

### Steps to reproduce

1. Run the example above
2. Notice how there are now two confirm buttons

### Environment

- v23

### Browsers Affected

N/A

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #2710

### CODE REVIEW

File: vaadin-confirm-dialog-flow-parent/vaadin-confirm-dialog-flow-integration-tests/src/main/java/com/vaadin/flow/component/confirmdialog/examples/FeaturesDiy.java [hunk 1]
```diff
@@ -19,6 +19,10 @@ protected ConfirmDialog createConfirmDialog(String sample) {
         dialog.setHeader(new H2("Meeting starting").getElement());
         dialog.setText(
                 new Span("Your next meeting starts in 5 minutes").getElement());
+
+        // This button will get discarded by the new confirm button added below.
+        dialog.setConfirmButton(new Button("Discaded confirm button"));
```
Comment (sissbruecker) [inline vaadin-confirm-dialog-flow-parent/vaadin-confirm-dialog-flow-integration-tests/src/main/java/com/vaadin/flow/component/confirmdialog/examples/FeaturesDiy.java:24]:
```suggestion
        dialog.setConfirmButton(new Button("Discarded confirm button"));
```

**Review by sissbruecker — APPROVED** [review]
