### PR TITLE
fix!: ensure only last Grid scroll invocation is sent to client

### LINKED ISSUE #5880: [Grid] scrollToEnd is always executed after scrollToStart regardless of their call order
### Description

`scrollToEnd` gets always executed after `scrollToStart` regardless of their call order in the code.

### Expected outcome

When `scrollToStart` comes after `scrollToEnd`, I'd expect the grid to scroll to the end and then to the start.

### Minimal reproducible example

```java
@Route("grid")
public class GridView extends Div {
    public GridView() {
        Grid<String> grid = new Grid<>();
        grid.addColumn(item -> item);
        grid.setItems(IntStream.range(0, 1000).mapToObj(i -> "Item " + i).collect(Collectors.toList()));

        Button scrollToEndAndStart = new Button("scroll to end and start", event -> {
            grid.scrollToEnd();
            grid.scrollToStart();
        });

        add(grid, scrollToEndAndStart);
    }
}
```

### Steps to reproduce

1. Click "scroll to end and start"
2. See that the grid's scroll position is at the end while I'd expect it at the start

### Environment

Vaadin version(s): 24.4 and earlier
OS: Mac OS

### Browsers

_No response_

### PR DESCRIPTION
**Pull request by vursen**
When multiple Grid scroll methods were called in the same round-trip (e.g. `scrollToEnd()` followed by `scrollToStart()`), `scrollToEnd` was always executed last regardless of call order. This happened because `scrollToEnd` used `beforeClientResponse` to defer its execution, while `scrollToIndex`/`scrollToStart` executed immediately so the deferred `scrollToEnd` always won.

This PR adds a `scheduleScrollExecution` helper in Grid that defers scroll actions via `runWhenAttached` + `beforeClientResponse` and cancels any previously scheduled scroll, so only the last call in a round-trip takes effect. All Grid and TreeGrid scroll methods now use this helper, which eliminates the call order issue.

Also, tests have been reorganized and extended to cover deduplication behavior for both Grid and TreeGrid.

> [!WARNING]
> This change can be considered behavior-altering since it changes the timing of `scrollToIndex` and `scrollToStart`.

Fixes #5880

### CODE REVIEW

File: vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java [hunk 1]
```diff
@@ -3305,6 +3308,26 @@ private void callJsFunctionBeforeClientResponse(String functionName,
...
+    /**
+     * Schedules a scroll-related action to be executed before the next client
+     * response. Cancels any previously scheduled scroll action, ensuring that
+     * only the last scroll call takes effect.
+     *
+     * @param action
+     *            the scroll action to execute
+     */
+    protected void scheduleScrollExecution(SerializableRunnable action) {
+        getElement().getNode().runWhenAttached(ui -> {
```
Comment (tomivirkki) [inline vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java:3320]: Would possibly be cleaner to store the SerializableRunnable action as such here synchronously (`this.pendingScrollAction = action`). Then you won't need to `remove()` any scheduled beforeClientResponse registrations.

File: vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java [hunk 2]
```diff
@@ -3305,6 +3308,26 @@ private void callJsFunctionBeforeClientResponse(String functionName,
...
+            if (pendingScrollRegistration != null) {
+                pendingScrollRegistration.remove();
+            }
+            pendingScrollRegistration = ui.beforeClientResponse(this, ctx -> {
+                action.run();
```
Comment (tomivirkki) [inline vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java:3325]: Grid may no longer be attached at this point. Maybe something like this would work:

```java
if (!grid.isAttached()) {
  scheduleScrollExecution(pending...)
} else {
 ....
}

```

Comment (vursen) [reply vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java:3325]: Does the new implementation actually change this behavior? Wasn't this already how the scroll methods worked?

Comment (tomivirkki) [reply vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java:3325]: I tested locally and my assumption was wrong. The current implementation actually handles this already. LGTM
