### PR TITLE
Shim an implementation of `getSubStringLength`

### LINKED ISSUE #5365: X-Axis labels overlapping in svg export
### Description

Vaadin charts with long x-axis labels is overlapping when exported as svg and then downloaded as pdf.  The labels get wrapped in browser but not in the svg. Also when the chart is rendered in small space then the labels are displayed with ellipsis but the generated svg looks much different with respect to labels. 

### Expected outcome

The labels should be wrapped or displayed with ellipsis. 

### Minimal reproducible example
```
public MainView() throws TranscoderException {
		String filepath = "path_to_location/test.pdf";
		Chart chart = new Chart();
		Configuration configuration = chart.getConfiguration();
		configuration.setTitle("");
		configuration.setSubTitle("");
		chart.getConfiguration().getChart().setType(ChartType.COLUMN);

		String months[] = { "January", "February", "March", "April" };
		int survey[][] = { // ETG Base
				{ 8, 0, 7, 0 }, // 164800 obesity
				{ 30, 1, 30, 2 }, // 388100 Hypertension
				{ 37, 0, 22, 2 }, // TQA or pharyngitis
				{ 13, 23, 4, 1 }, // Other skin inflamation
				{ 3, 10, 9, 0 }, // Exposure to infectious disease
		};

		for (int month = 0; month < 4; month++) {
			ListSeries series = new ListSeries();
			for (int num = 0; num < survey.length; num++)
				series.addData(survey[num][month]);
			configuration.addSeries(series);
		}

		XAxis xaxis = new XAxis();
		xaxis.setCategories("164800 obesity", "388100 Hypertension", "TQA or pharyngitis",
				"Other dangerous skin inflamations",
				"Exposure to deadly infectious disease");
		xaxis.setTitle("ETG Base");
		configuration.addxAxis(xaxis);

		Div div = new Div();
		add(div);

		Button downloadButton = new Button("download");
		downloadButton.addClickListener(event -> {
			try (SVGGenerator generator = new SVGGenerator()) {
				ExportOptions exportOptions = new ExportOptions();
				Theme theme = new Theme();

				Legend legend = theme.getLegend();
				legend.setItemMarginTop(50);
				Style titileStyle = theme.getxAxis().getTitle();
				titileStyle.setTop("500px");
				theme.setTitle(titileStyle);
				exportOptions.setTheme(theme);

				String svg = generator.generate(configuration, exportOptions);

				div.getElement().setProperty("innerHTML", svg);

				saveGeneratedSvgAsPdf(svg, filepath);

			} catch (IOException | InterruptedException | TranscoderException ex) {
				// handle exceptions accordingly
			}
		});
		add(downloadButton);
		add(chart);
	}

	public void saveGeneratedSvgAsPdf(String svg, String filePath) throws TranscoderException, FileNotFoundException {

		Transcoder transcoder = new PDFTranscoder();
		TranscoderInput transcoderInput = new TranscoderInput(
				new ByteArrayInputStream(svg.getBytes(StandardCharsets.UTF_8)));
		TranscoderOutput transcoderOutput = new TranscoderOutput(new FileOutputStream(new File(filePath)));
		transcoder.transcode(transcoderInput, transcoderOutput);
	}
```
### Steps to reproduce

1.  Add the above code to any vaadin project (Tested in Version 14 and Version24)
2.  Update the filepath. 
3.  Click on the download button.

### Environment

Vaadin version(s): Tested in V14 with vaadin-charts-flow version 21.0.2 and Vaadin 24 with vaadin-charts-flow version 24.1.4
OS: Windows

### Browsers

Chrome

### PR DESCRIPTION
**Pull request by aroneous**
This is a second attempt at the fix originally submitted under #5373

Estimate the rendered length of a substring of text in an SVG element. Supports wrapping/truncation of long labels in charts.
Do not consider `<title>` tags in size calculations.

jsdom does not support layout/sizing logic, but some amount of this is required for Highcharts to work correctly. The Highcharts logic to handle wrapping and truncation of long labels relies on the SVG `getSubStringLength` method. Add a shim for this method, which estimates the rendered length of a substring of text. Follow the same basic strategy as used in the existing `getBBox` shim.

When text is truncated, Highcharts inserts a `<title>` element in the SVG with the full text. `getBBox` was considering these elements when computing dimensions. However, these aren't rendered on the screen (they specify tooltips), so this threw off the size calculations and resulted in poor behavior when rendering charts with truncated labels. Stop processing `<title> `elements in `getBBox`.

Update `getBBox` and implement `getSubStringLength` to better handle arbitrary DOM structures.

Use the string-pixel-width library to improve estimation of rendered string length, in both `getBBox` and `getSubStringLength`.

Update 'expected' SVG for tests, as it changes (in a good direction, hopefully) layout.

Fixes #5365

### CODE REVIEW

File: vaadin-charts-flow-parent/vaadin-charts-flow-svg-generator/jsdom-exporter.js [hunk 1]
```diff
@@ -138,6 +200,67 @@ doc.createElementNS = (ns, tagName) => {
...
+                return;
+            }
+
+            if (remaining <= 0) {
+                return;
+            }
+            let childLength = textNode.length;
+
+            if (childLength <= offset) {
+                offset -= childLength;
```
Comment (DiegoCardoso) [inline vaadin-charts-flow-parent/vaadin-charts-flow-svg-generator/jsdom-exporter.js:237]: None of the current tests seems to hit this condition. Adding at least one test where this condition happens would be a good idea.

File: vaadin-charts-flow-parent/vaadin-charts-flow-svg-generator/jsdom-exporter.js [hunk 2]
```diff
@@ -76,56 +131,63 @@ doc.createElementNS = (ns, tagName) => {
...
+            newLine = false;
 
         let children = [].slice.call(
             elem.children.length ? elem.children : [elem]
         );
+        children.forEach(child => {
+            if (child.getAttribute('class') === 'highcharts-text-outline') {
+                child.parentNode.removeChild(child);
+            }
+        });
```
Comment (DiegoCardoso) [inline vaadin-charts-flow-parent/vaadin-charts-flow-svg-generator/jsdom-exporter.js:146]: nit: this code happens twice in this file, it could be refactored into a helper function.

**Review by DiegoCardoso — CHANGES_REQUESTED** [review]
Thanks for your contribution. The changes seem to work as expected. Here are my first few comments on the PR.

File: vaadin-charts-flow-parent/vaadin-charts-flow-svg-generator/jsdom-exporter.js [hunk 3]
```diff
@@ -45,6 +51,55 @@ require("highcharts/modules/bullet")(Highcharts);
 
 win.Date = Date;
 
+function processTextNodes(element, cb, parents = []) {
```
[the remark this answers is not in the document]
Comment (aroneous) [reply vaadin-charts-flow-parent/vaadin-charts-flow-svg-generator/jsdom-exporter.js:54]: No, it can be removed. It was used in my initial implementation, but I moved away from it.

[the remark this answers is not in the document]
Comment (aroneous) [reply vaadin-charts-flow-parent/vaadin-charts-flow-svg-generator/jsdom-exporter.js]: Removed

File: vaadin-charts-flow-parent/vaadin-charts-flow-svg-generator/jsdom-exporter.js [hunk 4]
```diff
@@ -76,56 +131,63 @@ doc.createElementNS = (ns, tagName) => {
...
+            // copied from the SVGRenderer.fontMetrics function in
+            // Highcharts.
+            if (/px/.test(fontSize)) {
+                fontSize = parseInt(fontSize, 10);
+            } else {
+                fontSize = /em/.test(fontSize) ?
+                    parseFloat(fontSize) * 12 :
+                    12;
+            }
+            let nodeHeight =fontSize < 24 ?
```
[the remark this answers is not in the document]
Comment (aroneous) [reply vaadin-charts-flow-parent/vaadin-charts-flow-svg-generator/jsdom-exporter.js]: Fixed

File: vaadin-charts-flow-parent/vaadin-charts-flow-svg-generator/jsdom-exporter.js (hunk 2 above)
Comment (aroneous) [reply vaadin-charts-flow-parent/vaadin-charts-flow-svg-generator/jsdom-exporter.js]: Done

File: vaadin-charts-flow-parent/vaadin-charts-flow-svg-generator/jsdom-exporter.js (hunk 1 above)
Comment (aroneous) [reply vaadin-charts-flow-parent/vaadin-charts-flow-svg-generator/jsdom-exporter.js]: I don't know of a good way to trigger this case through Highcharts chart generation, so I added a mocha test to directly invoke it. I changed the way the shims were added to elements to enable that testing (and I think it's a neater method, anyway).

Comment (DiegoCardoso) [reply vaadin-charts-flow-parent/vaadin-charts-flow-svg-generator/jsdom-exporter.js]: Cool. I actually had this same refactor in mind while I was reviewing this code. Patching the prototype seems to be a better alternative to what is currently being done.

**Comment by vursen** [comment]
I initially worried that `string-pixel-width` might not work for non-English captions, as it provides width estimations only for English characters. However, after looking into its implementation, it appears to have a fallback mechanism: when a character isn't found in the width map, it returns the width of `x`. I did some manual testing and confirmed that it seems to work quite well:

image

**Review by DiegoCardoso — APPROVED** [review]

**Review by vursen — APPROVED** [review]
