### PR TITLE
fix: set empty title option to avoid default title

### LINKED ISSUE #2743: Chart without title gets "Chart title" when exported by SVGGenerator
Vaadin 22.0.6

If have have title of the chart defined SVGGenerator works ok. But if I do not have a Title defined, the exported version will get dummy "Chart title", which I think is a bug. Also if I set title to be empty string, there will be still empty title there, which takes space. And this empty space reduces available space for the chart itself. 

Workaround:

At this point of time you can compensate this by adding some height to exported chart as a workaround.

Code to reproduce:

```
    public ColumnChart() {
        Chart chart = new Chart();
        chart.setHeight("300px");
        chart.setWidth("400px");

        Configuration configuration = chart.getConfiguration();
        chart.getConfiguration().getChart().setType(ChartType.COLUMN);

        configuration.addSeries(new ListSeries("Tokyo", 49.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4));
        configuration.addSeries(new ListSeries("New York", 83.6, 78.8, 98.5, 93.4, 106.0, 84.5, 105.0, 104.3, 91.2, 83.5, 106.6, 92.3));
        configuration.addSeries(new ListSeries("London", 48.9, 38.8, 39.3, 41.4, 47.0, 48.3, 59.0, 59.6, 52.4, 65.2, 59.3, 51.2));
        configuration.addSeries(new ListSeries("Berlin", 42.4, 33.2, 34.5, 39.7, 52.6, 75.5, 57.4, 60.4, 47.6, 39.1, 46.8, 51.1));

        XAxis x = new XAxis();
        x.setCrosshair(new Crosshair());
        x.setCategories("January is a long mont", "February is rather boring", "Mar", "Apr", "May", "Jun", "Jul", "Aug",
                "Sep", "Oct", "Nov", "Dec");
        configuration.addxAxis(x);

        YAxis y = new YAxis();
        y.setMin(0);
        y.setTitle("Rainfall (mm)");
        configuration.addyAxis(y);

        Tooltip tooltip = new Tooltip();
        tooltip.setShared(true);
        configuration.setTooltip(tooltip);

        Button export = new Button("Export");

        export.addClickListener(event -> {
            ExportOptions options = new ExportOptions();
            options.setWidth(400);
            options.setHeight(300);
            try (SVGGenerator generator = new SVGGenerator()) {
                String svg = generator.generate(configuration, options);
                Html html = new Html("<div>"+svg+"</div>");
                add(html);
            } catch (IOException | InterruptedException ex) {
                // handle exceptions accordingly
            }
        });
        add(chart, export);
```

image

### PR DESCRIPTION
**Pull request by alvarezguille**
The same null text title is part of the _baseConfig in the WC to avoid the default title from Highcharts.

Fixes #2743

### CODE REVIEW

File: vaadin-charts-flow-parent/vaadin-charts-flow-svg-generator/jsdom-exporter.js [hunk 1]
```diff
@@ -204,7 +204,8 @@ const jsdomExporter = ({ chartConfiguration, outFile = 'chart.svg', exportOption
                 }
             },
             credits: { enabled: false },
-            exporting: { enabled: false }
+            exporting: { enabled: false },
+            title:{ text : null }
```
Comment (web-padawan) [inline vaadin-charts-flow-parent/vaadin-charts-flow-svg-generator/jsdom-exporter.js:208]:
```suggestion
            title: { text : null }
```

**Review by DiegoCardoso — APPROVED** [review]
