### PR TITLE
fix: make waitForUploads poll for upload processing until completion or timeout

### LINKED ISSUE #3646: Testbench: UploadElement#waitForUploads is not working as expected
### Description

We've had some random ScriptTimeoutExceptions in the past when trying to upload something with the ``UploadElement`` despite the upload being successful.

There seems to be a problem inside https://github.com/vaadin/flow-components/blob/ed8011f6d12d504d150f52845ce650831d06e604/vaadin-upload-flow-parent/vaadin-upload-testbench/src/main/java/com/vaadin/flow/component/upload/testbench/UploadElement.java#L131-L149

#### Problem description
This method set's Selenium's script timeout to ``maxSeconds`` (default ``60``).
However the whole script that checks if the uploads are finished is executed only once: After 500ms with ``setTimeout``.
So if the upload isn't finished after ``500ms`` (it may be finished after e.g. ``700ms``) the ``callback()`` is never executed, thus Selenium throws ``ScriptTimeoutException``.

#### Applied workaround
```java
public void waitForUploads(final int maxSeconds)
{
      final WebDriver.Timeouts timeouts = this.getDriver().manage().timeouts();
      timeouts.scriptTimeout(Duration.ofSeconds(maxSeconds));
      
      final String script = "var callback = arguments[arguments.length - 1];"
	      + "var upload = arguments[0];"
	      + "function checkUploads(counter) {"
	      + "  if (counter > " + (maxSeconds * 5) + ") return;"
	      + "  window.setTimeout(function() {"
	      + "    var inProgress = upload.files.filter(function(file) { return file.uploading;}).length > 0;"
	      + "    if (!inProgress) {"
	      + "      callback();"
	      + "    } else {"
	      + "      checkUploads(++counter);"
	      + "    }"
	      + "  }, 195);"
	      + "};"
	      + "checkUploads(0);";
      this.getCommandExecutor().getDriver().executeAsyncScript(script, this);
}
```

### Expected outcome

Upload works, even when it takes more than ``500ms``

### Minimal reproducible example

```java
this.$(UploadElement.class).first().upload(file);
```

### Steps to reproduce

Upload anything with ``UploadElement#upload``. The upload should take longer than 1s (e.g. slower PC, bigger file, etc).
Hint: We use [Testcontainers](https://www.testcontainers.org/modules/webdriver_containers/) so a RemoteWebdriver is used.

### Environment

Vaadin version(s): 23.1.7
OS: -

### Browsers

_No response_

### PR DESCRIPTION
**Pull request by mcollovati**
## Description

Currently UploadElement.waitForUploads checks for in-progress uploads only once causing the test to fail if the upload does not complete in 500 milliseconds. This change repeats the check every 500 milliseconds, until the condition is verified or the script execution times out.

Fixes #3646

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/contributing/overview
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.
- [x] I have not completed some of the steps above and my pull request can be closed immediately.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

File: vaadin-upload-flow-parent/vaadin-upload-testbench/src/main/java/com/vaadin/flow/component/upload/testbench/UploadElement.java [hunk 1]
```diff
@@ -151,10 +151,13 @@ private void waitForUploads(int maxSeconds) {
         timeouts.setScriptTimeout(maxSeconds, TimeUnit.SECONDS);
 
         String script = "var callback = arguments[arguments.length - 1];"
```
Comment (vursen) [inline vaadin-upload-flow-parent/vaadin-upload-testbench/src/main/java/com/vaadin/flow/component/upload/testbench/UploadElement.java:153]: Could we avoid using setInterval and implement this with waitUtil? My concern is that setInterval can run forever in the background if the web component gets stuck in the inProgress state.

Comment (mcollovati) [reply vaadin-upload-flow-parent/vaadin-upload-testbench/src/main/java/com/vaadin/flow/component/upload/testbench/UploadElement.java:153]: Make sense. Let me make a try

Comment (mcollovati) [reply vaadin-upload-flow-parent/vaadin-upload-testbench/src/main/java/com/vaadin/flow/component/upload/testbench/UploadElement.java:153]: BTW, is it OK to use Java multiline strings or should the change be compatible with older Java versions?

Comment (mcollovati) [reply vaadin-upload-flow-parent/vaadin-upload-testbench/src/main/java/com/vaadin/flow/component/upload/testbench/UploadElement.java:148]: done

Comment (mcollovati) [reply vaadin-upload-flow-parent/vaadin-upload-testbench/src/main/java/com/vaadin/flow/component/upload/testbench/UploadElement.java:148]: Thanks. I'll update the PR

File: vaadin-upload-flow-parent/vaadin-upload-testbench/src/main/java/com/vaadin/flow/component/upload/testbench/UploadElement.java [hunk 2]
```diff
@@ -147,20 +145,15 @@ public void removeFile(int index) {
...
-                + "}, 500);";
-        getCommandExecutor().getDriver().executeAsyncScript(script, this);
-
+                + "var upload = arguments[0];" //
+                + "var inProgress = upload.files.filter(function(file) { return file.uploading;}).length >0;"
+                + "callback(!inProgress);";
+
+        waitUntil(
+                driver -> (Boolean) getCommandExecutor().getDriver()
+                        .executeAsyncScript(script, UploadElement.this),
```
Comment (vursen) [inline vaadin-upload-flow-parent/vaadin-upload-testbench/src/main/java/com/vaadin/flow/component/upload/testbench/UploadElement.java:155]: I guess this can be transformed to executeScript now that the script is synchronous.

Comment (mcollovati) [reply vaadin-upload-flow-parent/vaadin-upload-testbench/src/main/java/com/vaadin/flow/component/upload/testbench/UploadElement.java]: fixed

**Review by vursen — APPROVED** [review]

File: vaadin-upload-flow-parent/vaadin-upload-testbench/src/main/java/com/vaadin/flow/component/upload/testbench/UploadElement.java [hunk 3]
```diff
@@ -147,17 +145,10 @@ public void removeFile(int index) {
...
-                + "var upload = arguments[0];"
-                + "window.setTimeout(function() {"
-                + "  var inProgress = upload.files.filter(function(file) { return file.uploading;}).length >0;"
-                + "  if (!inProgress) callback();" //
-                + "}, 500);";
-        getCommandExecutor().getDriver().executeAsyncScript(script, this);
+        String script = "return arguments[0].files.every((file) => !file.uploading);";
 
+        waitUntil(driver -> (Boolean) getCommandExecutor().getDriver()
+                .executeScript(script, UploadElement.this), maxSeconds);
```
Comment (vursen) [inline vaadin-upload-flow-parent/vaadin-upload-testbench/src/main/java/com/vaadin/flow/component/upload/testbench/UploadElement.java:151]:
```suggestion
        waitUntil(driver -> (Boolean) getCommandExecutor()
                .executeScript(script, UploadElement.this), maxSeconds);
```

Comment (mcollovati) [reply vaadin-upload-flow-parent/vaadin-upload-testbench/src/main/java/com/vaadin/flow/component/upload/testbench/UploadElement.java:151]: `driver.executeScript` does not work because `driver` is a `WebDriver` instead of `TestBenchDriverProxy`.
I'll go for the first suggestion

Comment (mcollovati) [reply vaadin-upload-flow-parent/vaadin-upload-testbench/src/main/java/com/vaadin/flow/component/upload/testbench/UploadElement.java]: done

**Review by vursen — APPROVED** [review]
