### PR TITLE
fix: grid scroll to index after setting size

### LINKED ISSUE #5375: Grid.scrollTo does not work
### Description

When you add a Grid to a page or dialog and call scrollTo it does not work. It only works if the grid is already attached to the page. We encountered this problem after updating Vaadin to 23.3.13.
This bug was introduced by this commit: https://github.com/vaadin/flow-components/commit/b86e528

### Expected outcome

The scrollTo function also work when you add a Grid to a page.

### Minimal reproducible example

```
import java.util.ArrayList;
import java.util.List;

import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.dialog.Dialog;
import com.vaadin.flow.component.grid.Grid;
import com.vaadin.flow.component.html.Div;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.Route;

@Route("test")
public class TestView extends Div{

	public TestView() {
		setSizeFull();
		Button btn = new Button("Test");
		add(btn);
		btn.addClickListener(e -> onClick());
	}
	
	private void onClick() {
		Dialog dialog = new Dialog();
		dialog.setWidth("80%");
		dialog.setHeight("80%");
		
		VerticalLayout vLayout = new VerticalLayout();
		vLayout.setSizeFull();
		dialog.add(vLayout);
		
		Grid<Integer> grid = new Grid<Integer>();
		grid.setWidthFull();
		grid.setHeight("400px");
		grid.addColumn(e -> e.toString());
		vLayout.add(grid);
		
		grid.setItems(new ArrayList<>());
		
		List<Integer> items = new ArrayList<>();
		for(int i = 0; i < 1000; i++) {
			items.add(i);
		}
		grid.setItems(items);
		grid.getSelectionModel().select(300);
		grid.scrollToIndex(300);
		
		Button btn = new Button("Close");
		vLayout.add(btn);
		btn.addClickListener(e -> dialog.close()); 
		
		Button clickBtn = new Button("Click");
		vLayout.add(clickBtn);
		clickBtn.addClickListener(e -> {
			grid.setItems(new ArrayList<>());
			
			grid.setItems(items);
			grid.getSelectionModel().select(300);
			grid.scrollToIndex(300);
		}); 
		
		dialog.open();
	}
}


### Steps to reproduce

Click the "Test" button. You will see that the Grid is attached, but it didn't scroll to entry 300.
When you click the "Click" button in the dialog, the scrollTo works.

### Environment

Vaadin version(s): 23.3.13, 23.3.21
OS: Windows 10

### Browsers

Issue is not browser related

### PR DESCRIPTION
**Pull request by ugur-vaadin**
## Description

With the empty grid stuck in loading state [fix](https://github.com/vaadin/flow-components/pull/5043), it became possible that the size is set after `scrollToIndex` is called. This issue is only present in v23.3.

This PR uses `queueMicrotask` in order to delay the `scrollToIndex` call just enough to make sure that the size is initialized.

Fixes #5375 

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/contributing/overview
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

### CODE REVIEW

File: vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js [hunk 1]
```diff
@@ -1193,6 +1193,10 @@ import { isFocusable } from '@vaadin/grid/src/vaadin-grid-active-item-mixin.js';
             }
           })
         );
+
+        grid.scrollToIndex = tryCatchWrapper(function (index) {
```
Comment (tomivirkki) [inline vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js:1197]: Would it work if the `queueMicrotask` was added to the invocation (in Grid and TreeGrid)? Overriding a grid function and making it async somehow feels dangerous.

Comment (ugur-vaadin) [reply vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js:1197]: Sure, that makes sense.

Comment (ugur-vaadin) [reply vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js]: Done.

**Review by tomivirkki — APPROVED** [review]
