### PR TITLE
fix: delete selected key when input is cleared

### LINKED ISSUE #2222: Dropdown selection is not cleared when removing value set using `setValue()`
### Description

When setting a value to a ComboBox using method ```setValue()``` I observe the following behavior when trying to clear the value by using the clear button:
- If I clear the value via the clear button and then open the dropdown, it does not show the selected value anymore which is okay.
- But if before I click the clear button I open the dropdown (I see the selected value in the dropdown and in the input field) and then I close it again and I go and click the clear button,  I see the value cleared from the input field (so there's no selected value anymore) but if I open the dropdown again, the value is still shown as selected there. (See attachment below).

### Expected outcome

Clicking clear button after setting a value through ```setValue``` method should clear input value and selection value in dropdown.

### Actual outcome

Clicking clear button after setting a value through ```setValue``` method does not clear the selected value in dropdown.

### Live Demo
combobox-clear-issue

### Minimal reproducible example
```
List<String> items = new ArrayList<>(Arrays.asList("Anna", "Thomas", "Annabella", "John", "Tom", 
"William", "Henry", "Johnatan", "Anthony", "Anne"));            
ComboBox comboBox = new ComboBox<>("Select", items);
comboBox.setClearButtonVisible(true);

comboBox.addValueChangeListener(e -> {
  if(e.getValue() != null) {
    message.setText("New selected value: " + e.getValue());
  } else {
    message.setText("No value selected");
  }        
});

comboBox.setValue("Tom");
```
### Steps to reproduce

1. Add a ComboBox component to a page.
2. Add a list of items to the ComboBox.
3. Set clear button visible for the component.
4. Use ```setValue()``` method to set a value from the list of items.
5. After loading, open the dropdown and see the value selected.
6. Close the dropdown.
7. Click clear button to clear the selected value.
8. Open dropdown again. Value is still shown as selected.

### Environment

Vaadin platform 14.7.1.

### Browsers Affected
Tested on Chrome.

### PR DESCRIPTION
**Pull request by web-padawan**
## Description

The internal `_selectedKey` state is not maintained on the server so should be enough to clear it in the connector.

Fixes #2222

## Type of change

- Bugfix

### CODE REVIEW

File: vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/ClearValueIT.java [hunk 1]
```diff
@@ -126,6 +127,28 @@ public void allowCustomValue_enterCustomValue_setNullValue_inputElementValueIsCl
         Assert.assertEquals("", comboBox.getInputElementValue());
     }
 
+    @Test
+    public void allowCustomValue_openPopup_clearButton_selectedItemIsReset() {
+        ComboBoxElement comboBox = $(ComboBoxElement.class)
+                .id(ClearValuePage.COMBO_BOX_WITH_ALLOW_CUSTOM_VALUE_ID);
```
Comment (tomivirkki) [inline vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/ClearValueIT.java:133]: Even though the test passes, it seems to be using a wrong ComboBox

https://user-images.githubusercontent.com/1222264/150092050-84331715-27ac-4449-8a17-3e725304507f.mp4

Comment (web-padawan) [reply vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/ClearValueIT.java]: My bad, copied the wrong test 🙈   Updated.

**Review by tomivirkki — APPROVED** [review]

File: vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/resources/META-INF/resources/frontend/comboBoxConnector.js [hunk 2]
```diff
@@ -260,6 +260,11 @@ import { ComboBoxPlaceholder } from '@vaadin/combo-box/src/vaadin-combo-box-plac
                 }
             }), { once: true });
 
+            comboBox.addEventListener('value-changed', tryCatchWrapper((event) => {
+                if (comboBox._selectedKey && !event.detail.value) {
+                    delete comboBox._selectedKey;
```
[the remark this answers is not in the document]
Comment (web-padawan) [reply vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/resources/META-INF/resources/frontend/comboBoxConnector.js:265]: Web component issue was fixed by https://github.com/vaadin/web-components/pull/3307
