### PR TITLE
fix: add polyfill to trigger context-menu on long press

### LINKED ISSUE #5787: Spreadsheet context menu doesn't work on touch devices
### Description

We expected to be able to use context menus via long-press now in V24, but Spreadsheet at least doesn't support it.  This is not mentioned in the limitations, or that V8 context menu behavior is still there on touch devices.

I'll have to figure out how to shoehorn in the JavaScript changes I got to work in V8, even though the component now has the GWT build hidden away and the outputs committed instead.  

Happy to share that code if desired, but it removes the "Fill" option, as we don't use it.  Could make that an optional action folks could add to their context menus if they want it, rather than defaulting it.

Getting long-press to work on iOS is tricky as some versions don't support the ContextMenu event, so you have to implement it with timers, but the code is well established.

We have many iPad users, so I need a workaround and/or fix.  Happy to discuss options either way, and demo my v8 code.

### Expected outcome

long-pressing on a cell on a touch device should bring up the context menu if one is defined, such as ```SpreadsheetDefaultActionHandler```.

### Minimal reproducible example

https://demo.vaadin.com/spreadsheet/

on desktop there are context actions available, but on touch devices I see the V8 behavior still, which is just the "Fill" action. 

### Steps to reproduce

right click on a cell in any demo, on desktop, then try it on a touch device (iPad, phone, etc.).

### Environment

Vaadin version(s): 24.2.4
OS: N/A

### Browsers

Issue is not browser related

### PR DESCRIPTION
**Pull request by DiegoCardoso**
## Description

Add a polyfill to trigger context-menu events for long presses in iOS devices.

The polyfill is heavily based on this one provided by @WoozyG in [his comment on the issue he reported](https://github.com/vaadin/flow-components/issues/5787#issuecomment-1832744531).

The polyfill only triggers the context-menu event when the user presses down for more than 750 milliseconds. The event is handled by the same method that handles the click button, except that it now checks for the type of the event for the cases where the right click should be handled.

Below a demonstration of the feature working on a iPhone:

https://github.com/vaadin/flow-components/assets/262432/45bbbc94-706b-417c-a81d-7b994f6fee8c

Not sure yet how to add tests for this behavior.

Fixes #5787

## Type of change

- [X] Bugfix
- [ ] Feature

### CODE REVIEW

File: vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/SpreadsheetContextMenuPolyfill.java [hunk 1]
```diff
@@ -0,0 +1,132 @@
...
+ * On touch start, a timer is started. If the user releases the touch before the
+ * timer expires, the timer is cancelled. If the user moves the touch before the
+ * timer expires, the timer is cancelled. If the timer expires, a context menu
+ * event is triggered.
+ * </p>
+ *
+ */
+final class SpreadsheetContextMenuPolyfill implements TouchStartHandler,
+        TouchCancelHandler, TouchEndHandler, TouchMoveHandler {
+    final SpreadsheetWidget spreadsheetWidget;
```
Comment (ugur-vaadin) [inline vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/SpreadsheetContextMenuPolyfill.java:45]: Nit: 
```suggestion
    private final SpreadsheetWidget spreadsheetWidget;
```

File: vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/SpreadsheetContextMenuPolyfill.java [hunk 2]
```diff
@@ -0,0 +1,132 @@
...
+    /* default */ Timer timer;
```
Comment (ugur-vaadin) [inline vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/SpreadsheetContextMenuPolyfill.java:46]: Nit:
```suggestion
    private Timer timer;
```

**Review by ugur-vaadin — APPROVED** [review]
LGTM overall. Having another review with a suggestion on how to test could be beneficial.

File: vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/SpreadsheetWidget.java [hunk 3]
```diff
@@ -220,6 +226,24 @@ public void onAttachOrDetach(AttachEvent attachEvent) {
 
             }
         });
+
+        if (isTouchMode() && !BrowserInfo.get().isAndroid()) {
```
Comment (ugur-vaadin) [inline vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/SpreadsheetWidget.java:230]: Out of curiosity, why are we excluding Android?

File: vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/SheetWidget.java [hunk 4]
```diff
@@ -1141,7 +1142,8 @@ protected void onSheetMouseDown(Event event) {
 
         if (isEventInCustomEditorCell(event)) {
             // allow sheet context menu on top of custom editors
-            if (event.getButton() == NativeEvent.BUTTON_RIGHT) {
+            if (event.getButton() == NativeEvent.BUTTON_RIGHT
+                    || event.getType() == BrowserEvents.CONTEXTMENU) {
```
Comment (ugur-vaadin) [inline vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/SheetWidget.java:1146]: Nit based on Sonar:
```suggestion
                    || BrowserEvents.CONTEXTMENU.equals(event.getType())) {
```

File: vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/SheetWidget.java [hunk 5]
```diff
@@ -1185,7 +1187,8 @@ protected void onSheetMouseDown(Event event) {
 
             event.stopPropagation();
             event.preventDefault();
-            if (event.getButton() == NativeEvent.BUTTON_RIGHT) {
+            if (event.getButton() == NativeEvent.BUTTON_RIGHT
+                    || event.getType() == BrowserEvents.CONTEXTMENU) {
```
Comment (ugur-vaadin) [inline vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/SheetWidget.java:1191]: Nit based on Sonar:
```suggestion
                    || BrowserEvents.CONTEXTMENU.equals(event.getType())) {
```

File: vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/SpreadsheetWidget.java (hunk 3 above)
Comment (WoozyG) [reply vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/SpreadsheetWidget.java:230]: https://caniuse.com/mdn-api_element_contextmenu_event

iOS is the only mobile platform that doesn't support the `contextmenu` event.

Comment (DiegoCardoso) [reply vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/SpreadsheetWidget.java]: This is correct, but after this comment, I checked and the context menu wasn't showing up on long press in Android devices. That was because, although `contextmenu` is supported by Chrome in Android, the Spreadsheet client wasn't listening to any event of that type.

I refactored it to now listen to `contexmenu` event instead of checking for right-click on `mouseup` event.

File: vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/SheetWidget.java (hunk 4 above)
Comment (DiegoCardoso) [reply vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/SheetWidget.java]: Done.

File: vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/SheetWidget.java (hunk 5 above)
Comment (DiegoCardoso) [reply vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/SheetWidget.java]: Done.

File: vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/SpreadsheetContextMenuPolyfill.java (hunk 2 above)
Comment (DiegoCardoso) [reply vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/SpreadsheetContextMenuPolyfill.java]: Done.

File: vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/SpreadsheetContextMenuPolyfill.java (hunk 1 above)
Comment (DiegoCardoso) [reply vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/SpreadsheetContextMenuPolyfill.java]: Done.
