### PR TITLE
fix: prevent server value change for edited locked cells

### LINKED ISSUE #7940: [Spreadsheet] It is possible to update content of the cells in a locked sheet
### Description

When a cell is modified and the sheet is locked afterwards, the initially modified cells can still be updated after locking occurs.

### Expected outcome

I would expect that the cells are properly locked.

### Minimal reproducible example

Spreadsheet demo page can be used.

### Steps to reproduce

1. Create new spreadsheet
2. Update content on some of the cells
3. Load LockSheet fixture
4. Observe that previously modified cells can still be modified

### Environment

Vaadin version(s): 25.0
OS: MacOS

### Browsers

Issue is not browser related

### PR DESCRIPTION
**Pull request by ugur-vaadin**
## Description

Even when a cell is locked, it is still possible to update the server value when a client side cell edit event is received. This PR adds a layer of protection to the server side similar to when content is pasted onto locked cells. Now a `ProtectedEditEvent` is fired when a client side edit event for a locked cell is received.

Partially fixes #7940 

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/contributing/overview
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

### CODE REVIEW

File: vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/java/com/vaadin/flow/component/spreadsheet/SpreadsheetHandlerImpl.java [hunk 1]
```diff
@@ -131,6 +131,10 @@ public void selectionDecreasePainted(int r, int c) {
 
     @Override
     public void cellValueEdited(int row, int col, String value) {
+        if (spreadsheet.isCellLocked(new CellAddress(row, col))) {
```
Comment (sissbruecker) [inline vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/java/com/vaadin/flow/component/spreadsheet/SpreadsheetHandlerImpl.java]: The coordinates here are off:
- row and col seem to use a 1-based index
- CellAddress uses a 0-based index

File: vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/SpreadsheetWidget.java [hunk 2]
```diff
@@ -1777,6 +1777,7 @@ public void setSheetProtected(boolean sheetProtected) {
                         startDelayedSendingTimer();
                     }
                 }
+                sheetWidget.setCachedCellsLocked(sheetProtected);
```
Comment (sissbruecker) [inline vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/SpreadsheetWidget.java]: This also prevents editing unlocked cells. If I change `LockFixture` to mark a cell explicitly unlocked, it is not editable afterwards:
```java
        CellStyle unlockStyle = spreadsheet.getWorkbook().createCellStyle();
        unlockStyle.setLocked(false);

        Cell cell = spreadsheet.createCell(0, 0, 1);
        cell.setCellStyle(unlockStyle);
        spreadsheet.refreshCells(cell);

        spreadsheet.setActiveSheetProtected("pwd");
```

The same can probably done for unlocking rows or columns.

Comment (ugur-vaadin) [reply vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/SpreadsheetWidget.java]: I was considering changing `locked` field `CellData` from a primitive to an object in order to differentiate explicitly unlocked cells. I am not sure if it would break any existing configurations. What do you think?

File: vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/java/com/vaadin/flow/component/spreadsheet/SpreadsheetHandlerImpl.java (hunk 1 above)
Comment (ugur-vaadin) [reply vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/java/com/vaadin/flow/component/spreadsheet/SpreadsheetHandlerImpl.java]: Fixed.

File: vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/SpreadsheetWidget.java (hunk 2 above)
Comment (ugur-vaadin) [reply vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/SpreadsheetWidget.java]: Reverted client side changes.
