### PR TITLE
fix: access UI through container element in ComponentRenderer

### LINKED ISSUE #6751: [Regression] JS error occurs when ComponentRenderer is created in a background thread
### Description

The [refactoring](https://github.com/vaadin/flow-components/pull/4148) that updated the ComponentRenderer implementation to be based on LitRenderer introduced a regression: a JS error can now occur if ComponentRenderer is created in a background thread. This happens because the new implementation accesses UI using `UI.getCurrent()` unlike the previous implementation which used a different approach based on `runWhenAttached`. 

### Expected outcome

ComponentRenderer should retrieve the UI instance from the container element.

### Minimal reproducible example

The example below works without errors in Vaadin 23 but throws a JS error in Vaadin 24, resulting in an empty grid.

```java
@Push // <----- required
public class Application implements AppShellConfigurator {
```

```java
@Route("grid")
public class GridView extends Div {
    public GridView() {
        Button addGrid = new Button("Add grid", (event) -> {
            final VaadinSession session = VaadinSession.getCurrent();

            new Thread(() -> session.accessSynchronously(this::render)).start();
        });

        add(addGrid);
    }

    public void render() {
        Grid<String> grid = new Grid<>();
        grid.addColumn(new ComponentRenderer<Span, String>(item -> new Span(item)));
        grid.setItems("Item 1", "Item 2", "Item 3", "Item 4", "Item 5");
        add(grid);
    }
}
```

### Steps to reproduce

Click on the button and observe `Cannot read properties of undefined (reading 'getByNodeId')` in the browser console.

### Environment

Vaadin version(s): 24.0 and later

### Browsers

_No response_

### PR DESCRIPTION
**Pull request by vursen**
## Description

Using `UI.getCurrent()` isn't safe because even when the container is attached, it may return `null`. This PR updates the ComponentRenderer implementation to access the UI instance through the container element where it's guaranteed to be available if the container is attached.

Fixes #6751

## Type of change

- [x] Bugfix

### CODE REVIEW

File: vaadin-renderer-flow-parent/vaadin-renderer-flow-integration-tests/src/test/java/com/vaadin/flow/data/renderer/tests/ComponentRendererInNewThreadIT.java [hunk 1]
```diff
@@ -16,25 +16,43 @@
...
-    @Test
-    public void componentRendererInNewThread_uiNotNullWhileTemplateExpressionIsCalculated() {
+    @Before
+    public void init() {
         open();
-        findElement(By.id("add-component")).click();
+    }
+
+    @Test
+    public void addComponentRendererBeforeAttach_componentIsRendered() {
```
Comment (vursen) [inline vaadin-renderer-flow-parent/vaadin-renderer-flow-integration-tests/src/test/java/com/vaadin/flow/data/renderer/tests/ComponentRendererInNewThreadIT.java:36]: **note:** This test is a modern version of `componentRendererInNewThread_uiNotNullWhileTemplateExpressionIsCalculated` which covered https://github.com/vaadin/flow-components/pull/5534

**Review by tomivirkki — APPROVED** [review]

**Review by ugur-vaadin — APPROVED** [review]
