### PR TITLE
fix: handle empty node id in component renderer

### LINKED ISSUE #5830: ComboBox with custom renderer shows stale items before query finishes
### Description

When using a custom renderer with a ComboBox, when you open the dropdown you can see stale items before the fetch completes.  In my current project, we've run into multiple situations where this confuses users.

combobox-stale-render

### Expected outcome

If you do not use a renderer, the prev items are cleared when the dropdown is opened which I would expect to happen with a custom renderer as well.

### Minimal reproducible example

```
var cb = new ComboBox<Person>();
cb.setRenderer(item -> return new new Span(item.getFirstName() + " " + item.getLastName()));
cb.setItems(generateLargePersonBeanList());
```

### Steps to reproduce

1. add above snippet to view
2. open combobox and filter list, scroll down a bit 
3. close combobox
4. open again
5. while the fetch is completing (spinner at top right), you'll be able to see items from your previous filtered list (probably just a split second, longer fetches/slow connection makes longer)

### Environment

Vaadin version(s): 23.3.29
OS: Mac

### Browsers

Chrome, Firefox

### PR DESCRIPTION
**Pull request by ugur-vaadin**
## Description

This PR handles the empty nodeid case for Flow component renderer. This is already [handled](https://github.com/vaadin/flow-components/blob/8cebb28a0f8ecb55dc3e79c78da42b4831bcbb42/vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/resources/META-INF/resources/frontend/flow-component-directive.js#L34-L35) in the newer Flow component directive. With the new change, if a null/undefined node ID is received and there is a rendered child, it is removed.

Note: The test will succeed without the change in v24. The reason is that the Flow component renderer has already been refactored out of the renderer.

Note 2: There is no test added to the renderer package since I could not come up with a good test. This test is added to test at least the use-case provided in the related issue for this change.

Fixes #5830

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/contributing/overview
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

### CODE REVIEW

File: vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/resources/META-INF/resources/frontend/flow-component-renderer.js [hunk 1]
```diff
@@ -104,7 +104,11 @@ class FlowComponentRenderer extends PolymerElement {
   }
 
   _attachRenderedComponentIfAble() {
-    if (!this.nodeid || !this.appid) {
+    if (this.appid == null) {
+      return;
+    }
+    if (this.nodeid == null) {
+      this.remove(this.firstChild);
```
Comment (tomivirkki) [inline vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/resources/META-INF/resources/frontend/flow-component-renderer.js:111]: Use `removeChild` instead of [`remove`](https://developer.mozilla.org/en-US/docs/Web/API/Element/remove) (which removes the element itself, in this case, the `<flow-component-renderer>`, from its parent element). Note that `removeChild` throws if the given parameter is `undefined` (no child element).

Comment (ugur-vaadin) [reply vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/resources/META-INF/resources/frontend/flow-component-renderer.js]: Done.

File: vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/ComponentRendererIT.java [hunk 2]
```diff
@@ -66,14 +61,33 @@ public void captionsForItemsExistWhenFirstSettingDataProvider() {
...
+        for (int i = 0; i < 600; i += 50) {
+            scrollToItem(comboBox, i);
+        }
+
+        comboBox.closePopup();
+
+        String firstItemText = (String) executeScript("arguments[0].open();"
+                + "const item = document.querySelector('vaadin-combo-box-item');"
+                + "const spanInItem = item.querySelector('span');"
+                + "return spanInItem ? spanInItem.innerText : '';", comboBox);
```
Comment (vursen) [inline vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/ComponentRendererIT.java:87]: **nit:**

```suggestion
                + "return document.querySelector('vaadin-combo-box-item')?.textContent;", comboBox);
```

**Review by vursen — APPROVED** [review]
