### PR TITLE
fix: set fromClient to false on programmatic ContextMenu close

### LINKED ISSUE #6449: ContextMenu OpenedChangeEvent.isFromClient always returns true
### Description

Currently, `OpenedChangeEvent.isFromClient` returns true even if the menu was closed programmatically.

### Expected outcome

`OpenedChangeEvent.isFromClient` should return true if and only if the menu was actually closed through the UI

### Minimal reproducible example

[not provided]

### Steps to reproduce

1. Call `ContextMenu.close`
2. Catch the OpenChangeEvent on the contextmenu
3. Observe `.isFromClient` returning true

### Environment

Vaadin version(s): 24.4

### Browsers

Issue is not browser related

### PR DESCRIPTION
**Pull request by web-padawan**
## Description

Fixes #6449

## Type of change

- Bugfix

### CODE REVIEW

File: vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenuBase.java [hunk 1]
```diff
@@ -194,6 +200,7 @@ public boolean isOpenOnClick() {
      * Closes this context menu if it is currently open.
      */
     public void close() {
+        closedProgrammatically = true;
```
[the remark this answers is not in the document]
Comment (web-padawan) [reply vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenuBase.java:203]: It's set to `false` in the internal listener, see line 102 above.

File: vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenuBase.java [hunk 2]
```diff
@@ -194,6 +200,7 @@ public boolean isOpenOnClick() {
...
         getElement().callJsFunction("close");
```
Comment (sissbruecker) [inline vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenuBase.java:204]:
```suggestion
        getElement().setProperty("opened", false);
        getElement().callJsFunction("close");
```
This seems to work as well and doesn't require adding state.

Comment (web-padawan) [reply vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenuBase.java:204]: Thanks, tested it and it does work. Updated the PR.

**Review by sissbruecker — APPROVED** [review]
