### PR TITLE
fix: only use custom label when setting HTML

### LINKED ISSUE #2551: [checkbox] Label property defined in template is ignored when using `@Id`
### Description

There is an IT covering usage `<vaadin-checkbox>` in Polymer template with `@Id`:

https://github.com/vaadin/flow-components/blob/b3155936bbc319396b1021721f3eecd35b77d815/vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/frontend/inject-checkbox.js#L8

When updating the template to use `label` property instead of the default slot, it is ignored"

Screenshot 2022-01-24 at 16 17 23

### Expected outcome

The checkbox should have correct label `"Accept"`.

### Actual outcome

The label provided in template is getting overridden.

### Environment

- Vaadin 22 (stable) and 23 (alpha)

### PR DESCRIPTION
**Pull request by web-padawan**
## Description

Currently, the custom `<label>` is always created even if there is one provided by the user via template.
This PR changes it to use `label` property instead, and only create `<label>` when using `.setLabelAsHtml()`.

Also, updated the IT for the checkbox in template to ensure the `label` attribute value is preserved.

Fixes #2551

## Type of change

- Bugfix

### CODE REVIEW

File: vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/Checkbox.java [hunk 1]
```diff
@@ -138,7 +128,7 @@ private Label appendLabelElement() {
      */
     @Override
     public void setLabel(String label) {
-        labelElement.setText(label);
+        getElement().setProperty("label", label == null ? "" : label);
```
Comment (tomivirkki) [inline vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/Checkbox.java:131]: I'm guessing `getLabel()` wouldn't work after this change because it tries to find a `<label>` element from inside the component but now there's no server-side representation for it.

Comment (web-padawan) [reply vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/Checkbox.java:129]: Updated to use client-side property, same as for other components like `TextField`.

File: vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/Checkbox.java [hunk 2]
```diff
@@ -153,7 +141,11 @@ public void setLabel(String label) {
      *            the label html to set
      */
     public void setLabelAsHtml(String htmlContent) {
-        labelElement.getElement().setProperty("innerHTML", htmlContent);
+        // Create and add a new slotted label
```
Comment (tomivirkki) [inline vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/Checkbox.java:144]: We should call `setLabel("")` here. Otherwise after `setLabel("foo"); setLabelAsHtml("bar")`, `getLabel()` would return "foo". Related https://github.com/vaadin/flow-components/issues/1667

**Review by tomivirkki — CHANGES_REQUESTED** [review]

File: vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/Checkbox.java (hunk 2 above)
Comment (web-padawan) [reply vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/Checkbox.java]: Done.

File: vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/Checkbox.java [hunk 3]
```diff
@@ -153,7 +141,11 @@ public void setLabel(String label) {
...
+        Label label = new Label();
+        label.getElement().setAttribute("slot", "label");
+        label.getElement().setProperty("innerHTML", htmlContent);
+        getElement().appendChild(label.getElement());
```
[the remark this answers is not in the document]
Comment (web-padawan) [reply vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/Checkbox.java:152]: Updated to only create label once.

[the remark this answers is not in the document]
Comment (tomivirkki) [reply vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/Checkbox.java]: If we append the label element here, the Web Component results in state:
```
<vaadin-checkbox><label>html</label></vaadin-checkbo>
```
If `setLabel("new label")` is called afterwards, the result is:
```
<vaadin-checkbox label="new label"><label>html</label></vaadin-checkbo>
```
That would probably render "html", even though it should say "new label"?

[the remark this answers is not in the document]
Comment (web-padawan) [reply vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/Checkbox.java]: Updated `setLabel()` to remove custom label in case it's connected.

**Review by tomivirkki — APPROVED** [review]

**Review by yuriy-fix — APPROVED** [review]
