### PR TITLE
fix: retain spreadsheet styles correctly on disconnect and connect

### LINKED ISSUE #3369: [spreadsheet] Editing newly loaded spreadsheet does not work
### Description

"Been playing around with the 23.1 spreadsheet and it's working pretty well. One thing that doesn't seem to behave quite right is when you load a new workbook you can't just start typing (it throws an exception) you have to select the function bar then it works. Question is is there an API to select that from the java side or even the JS side? That would let us work around that issue without the user having to select the cell then click the formula bar."

```
spreadsheet:6 Tue Jun 21 08:50:00 GMT-600 2022 com.google.gwt.logging.client.LogConfiguration
SEVERE: (TypeError) : Cannot read properties of undefined (reading 'selectorText')
com.google.gwt.core.client.JavaScriptException: (TypeError) : Cannot read properties of undefined (reading 'selectorText')
at Unknown.GW(webpack-internal:///../target/flow-frontend/vaadin-spreadsheet/spreadsheet-export.js)
at Unknown.o$(webpack-internal:///../target/flow-frontend/vaadin-spreadsheet/spreadsheet-export.js)
at Unknown.f2(webpack-internal:///../target/flow-frontend/vaadin-spreadsheet/spreadsheet-export.js)
at Unknown.kW(webpack-internal:///../target/flow-frontend/vaadin-spreadsheet/spreadsheet-export.js)
at Unknown.pW(webpack-internal:///../target/flow-frontend/vaadin-spreadsheet/spreadsheet-export.js)
at Unknown.yI(webpack-internal:///../target/flow-frontend/vaadin-spreadsheet/spreadsheet-export.js)
at Unknown.dK(webpack-internal:///../target/flow-frontend/vaadin-spreadsheet/spreadsheet-export.js)
at Unknown.Kg(webpack-internal:///../target/flow-frontend/vaadin-spreadsheet/spreadsheet-export.js)
at Unknown.Ng(webpack-internal:///../target/flow-frontend/vaadin-spreadsheet/spreadsheet-export.js)
at Unknown.eval(webpack-internal:///../target/flow-frontend/vaadin-spreadsheet/spreadsheet-export.js)
```

### Expected outcome

Exception not thrown

### Minimal reproducible example

-

### Steps to reproduce

See description

### Environment

Vaadin version(s): 23.1

### Browsers

_No response_

### PR DESCRIPTION
**Pull request by ugur-vaadin**
## Description

When a spreadsheet is loaded right away, it is disconnected and connected again during the process. The styles are not retained correctly when it is connected again. 

This PR ensures that the styles are retained when this occurs. The relevant test is added.

Fixes #3369

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/contributing/overview
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

### CODE REVIEW

File: vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/resources/META-INF/resources/frontend/vaadin-spreadsheet/vaadin-spreadsheet.js [hunk 1]
```diff
@@ -196,15 +196,31 @@ export class VaadinSpreadsheet extends LitElement {
     super.connectedCallback()
     this.observer && this.observer.observe(this);
     // Restore styles in the case widget is reattached, it happens e.g in client router
-    this.styles && this.styles.forEach(e => document.head.appendChild(e));
+    let i = 0;
+    this.styles && this.styles.forEach(e => {
+      let addedNode = document.head.appendChild(e);
```
Comment (tomivirkki) [inline vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/resources/META-INF/resources/frontend/vaadin-spreadsheet/vaadin-spreadsheet.js:201]: No need to redefine a reference to the same node (`e` and `addedNode` here refer to the same node)

File: vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/resources/META-INF/resources/frontend/vaadin-spreadsheet/vaadin-spreadsheet.js [hunk 2]
```diff
@@ -196,15 +196,31 @@ export class VaadinSpreadsheet extends LitElement {
...
 
   disconnectedCallback() {
     super.disconnectedCallback();
     this.observer && this.observer.unobserve(this);
     // Remove styles added to the head by the Widget
     this.styles = document.head.querySelectorAll(`style[id^="spreadsheet-${this.id}"]`);
-    this.styles.forEach(e => document.head.removeChild(e));
+    this.removedRules = [];
+    this.styles.forEach(e => {
+      this.removedRules.push(e.sheet.cssRules);
```
Comment (tomivirkki) [inline vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/resources/META-INF/resources/frontend/vaadin-spreadsheet/vaadin-spreadsheet.js:221]: Let's avoid adding `this.removedRules` array and store the removed rules with the style element: `e.__removedRules = e.sheet.cssRules;`

File: vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/resources/META-INF/resources/frontend/vaadin-spreadsheet/vaadin-spreadsheet.js [hunk 3]
```diff
@@ -196,15 +196,31 @@ export class VaadinSpreadsheet extends LitElement {
     super.connectedCallback()
     this.observer && this.observer.observe(this);
     // Restore styles in the case widget is reattached, it happens e.g in client router
-    this.styles && this.styles.forEach(e => document.head.appendChild(e));
+    let i = 0;
+    this.styles && this.styles.forEach(e => {
+      let addedNode = document.head.appendChild(e);
+      if (this.removedRules) {
+        let rulesToBeAdded = this.removedRules[i];
```
Comment (tomivirkki) [inline vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/resources/META-INF/resources/frontend/vaadin-spreadsheet/vaadin-spreadsheet.js:203]: Use `const` when the value doesn't change.

**Review by tomivirkki — APPROVED** [review]
