### PR TITLE
fix: ensure upload i18n is preserved on reattach

### LINKED ISSUE #1849: Upload loses i18n
### Description

The upload component is losing the internationalization after re-navigation, when used in a `@UIScope`d view.

### Expected outcome

The configured `UploadI18N` is used.

### Actual outcome

The defaults are used.

### Minimal reproducible example

see https://github.com/chkpnt/vaadin-issue1849

### Steps to reproduce

1. Open a page (annotated with `@UIScope`) with an upload component that is configured with an `UploadI18N`
2. Navigate to another page
3. Navigate back to the page with the upload component (same instance)
4. The upload component doesn't use the provided `UploadI18N` anymore.

### Workaround

Reset the i18n in `beforeEnter(...)`.

### Environment

- v14.6.4
- macOS Big Sur 11.3.1

### Browsers Affected

- [x] Firefox
- [x] Chrome
- [ ] Safari (not tested)
- [ ] Edge (not tested)
- [ ] IE 11 (not tested)
- [ ] iOS Safari (not tested)
- [ ] Android Chrome (not tested)

### LINKED ISSUE #3521: Disappearing UploadI18N when switching tabs
### Description

When refreshing page with aTab selected all is fine. When switching to bTab and back to aTab i see "Upload File..." instead of "i18N_label"...

### Expected outcome

"i18N_label" should be still visible after switching between tabs

### Minimal reproducible example

```
@Route("")
public class MainView extends AppLayout {
    public MainView() {
        HorizontalLayout navbarLayout = new HorizontalLayout();
        Tab aTab = new Tab("A");
        Tab bTab = new Tab("B");
        Tabs tabs = new Tabs(aTab, bTab);
        navbarLayout.add(tabs);
        addToNavbar(navbarLayout);

        HorizontalLayout aLayout = new HorizontalLayout();
        MemoryBuffer memoryBuffer = new MemoryBuffer();
        Upload fileUpload = new Upload(memoryBuffer);
        UploadI18N i18N = new UploadI18N();
        i18N.setAddFiles(new UploadI18N.AddFiles().setOne("i18N_label"));
        fileUpload.setI18n(i18N);
        aLayout.add(fileUpload);
        setContent(aLayout);

        VerticalLayout bLayout = new VerticalLayout();
        bLayout.add(new H1("Placeholder"));

        tabs.addSelectedChangeListener(event -> {
                    String tabLabel = event.getSelectedTab().getLabel();
                    if (tabLabel.equals("A")) setContent(aLayout);
                    else if (tabLabel.equals("B")) setContent(bLayout);
                }
        );
    }
```

### Steps to reproduce

1. Run above code.

### Environment

Vaadin version(s): 23.1.1
OS: Windows

### Browsers

Chrome

### PR DESCRIPTION
**Pull request by web-padawan**
## Description

Fixes #3521
Fixes #1849

Some components that set `i18n` like `AppLayout` and `MenuBar` implement `onAttach` as follows:

https://github.com/vaadin/flow-components/blob/93105314241efb54c4b0e14d38739a2f5bba2564/vaadin-app-layout-flow-parent/vaadin-app-layout-flow/src/main/java/com/vaadin/flow/component/applayout/AppLayout.java#L122-L129

This logic was missing from `Upload`, so the client side `i18n` property was not updated.

## Type of change

- Bugfix

### CODE REVIEW

File: vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/test/java/com/vaadin/flow/component/upload/tests/UploadI18nIT.java [hunk 1]
```diff
@@ -112,6 +113,28 @@ public void testPartialI18nShouldSetFullConfigurationWithoutNullValuesInWebCompo
         assertTranslationMapHasNoMissingTranslations(translationMap);
     }
 
+    @Test
+    public void testDetachReattachI18nIsPreserved() {
+        open();
+
+        NativeButtonElement btnSetI18n = $(NativeButtonElement.class)
+                .id("btn-set-i18n");
```
Comment (DiegoCardoso) [inline vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/test/java/com/vaadin/flow/component/upload/tests/UploadI18nIT.java:121]: Since the test only needs the buttons to perform the click action, this could be done with:
```suggestion
        var btnSetI18n = findElement(By.id("btn-set-i18n"));
```

Doing so, importing the `flow-html-components-testbench` module wouldn't be needed.

**Review by DiegoCardoso — CHANGES_REQUESTED** [review]

File: vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/test/java/com/vaadin/flow/component/upload/tests/UploadI18nIT.java (hunk 1 above)
Comment (web-padawan) [reply vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/test/java/com/vaadin/flow/component/upload/tests/UploadI18nIT.java]: Thanks, done.

**Review by DiegoCardoso — APPROVED** [review]
LGTM 🎉
