### PR TITLE
fix: only use first column with no multi-sorting

### LINKED ISSUE #3155: Grid.sort considers only the first element of List<GridSortOrder> when creating the View
### Description

When I generate a new View that is containing a `Grid` ordered with more than one `GridSortOrder`, only the first  `GridSortOrder` is considered.
If I sort the grid again after the view has been fully generated, for example with a client event, all the orders are applied.

### Expected outcome

I would expect that the grid gets shown with all sorting orders at loading.

### Minimal reproducible example

Based on this minimal view example:
```java
import java.util.ArrayList;
import java.util.List;
import java.util.Random;

import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.grid.Grid;
import com.vaadin.flow.component.grid.Grid.Column;
import com.vaadin.flow.component.grid.GridSortOrder;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.Route;

@Route
public class MainView extends VerticalLayout {
	private Random r = new Random();
    public MainView() {
    	Grid<MyPojo> grid = new Grid<>();
    	Column<MyPojo> aCol = grid.addColumn(p -> p.getA()).setHeader("A").setAutoWidth(true).setFlexGrow(1).setSortable(true);
    	Column<MyPojo> bCol = grid.addColumn(p -> p.getB()).setHeader("B").setAutoWidth(true).setFlexGrow(1).setSortable(true);
    	grid.setItems(generateData());
    	this.add(grid);
    	grid.sort(GridSortOrder.asc(bCol).thenDesc(aCol).build()); // Here, only bCol is applied
    	Button b = new Button("Sort again");
    	b.addClickListener(click -> grid.sort(GridSortOrder.asc(bCol).thenDesc(aCol).build())); // Both bCol and aCol are applied
    	add(b);
    }
    private List<MyPojo> generateData() {
    	List<MyPojo> data = new ArrayList<>();
    	for (int i = 0; i < 20; i++) {
    		MyPojo o = new MyPojo();
    		o.setA(r.nextInt(100));
    		o.setB(r.nextInt(3));
    		data.add(o);
    	}
    	return data;
    }
    public class MyPojo {
    	int a, b;
    	public int getA() { return a;}
    	public void setA(int a) { this.a = a; }
    	public int getB() { return b; }
    	public void setB(int b) { this.b = b; }
    }
}
```

### Steps to reproduce

Run the view in the example
When the page is loaded, column A is random and B is ordered
When the button "Sort again" is pressed, B is ordered and A is correctly ordered.

### Environment

Vaadin version(s): 23.0.9
spring-boot-starter-parent: 2.6.7
JVM: OpenJDK 18.0.1
OS: MacOS 12.3.1
Browser: Chrome Version 101.0.4951.54 (Official Build) (x86_64)

### Browsers

Chrome

### PR DESCRIPTION
**Pull request by web-padawan**
## Description

This PR addresses the bug reported in https://github.com/vaadin/flow-components/issues/3155#issuecomment-1122477130:

> when clicking the button, the grid sorts by multiple columns, even though multi-sort is not enabled. 

Closes #3155

## Type of change

- Bugfix

### CODE REVIEW

File: vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java [hunk 1]
```diff
@@ -3246,6 +3249,9 @@ public void sort(List<GridSortOrder<T>> order) {
         if (order == null) {
             order = Collections.emptyList();
         }
+        if (!isMultiSort() && order.size() > 1) {
+            order = order.subList(0, 1);
```
Comment (tomivirkki) [inline vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java:3253]: Should a warning also be shown as suggested in https://github.com/vaadin/flow-components/issues/3155#issuecomment-1135755378?

Comment (web-padawan) [reply vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java:3255]: Thanks, added a warning.

**Review by tomivirkki — APPROVED** [review]
