### PR TITLE
fix: handle absolutely positioned images in XSSF files

### LINKED ISSUE #3261: [spreadsheet] Importing spreadsheet files works unexpectedly
Importing the test file `picture_sheet.xlsx` works unexpectedly. The outcome looks a bit different each time.

V8 Spreadsheet (expected):
Screenshot 2022-06-01 at 16 04 49

V23 Spreadsheet:
Screenshot 2022-06-01 at 16 05 50

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #3261

This PR fixes the issue by adding special handling for type 3 images (`DONT_MOVE_AND_RESIZE`) defined in XSSF files. The new logic anchors the images to the first cell (`A1`) and then applies x/y offset obtained from `xssfAnchor.getPosition()` as advised in https://github.com/vaadin/flow-components/issues/3261#issuecomment-1291256453

Using absolutely positioned images still has some issues after this change. They can be covered separately: 
- switching to a sheet with a large initial scrollTop doesn't show the image until scrolled back to the top
- sheets with frozen panes have problems with positioning the image

This PR also migrates a related IT from V8 Spreadsheet ([ImageTests](https://github.com/vaadin/spreadsheet/blob/flow-port/legacy/vaadin-spreadsheet/src/test/java/com/vaadin/addon/spreadsheet/test/ImageTests.java))

### CODE REVIEW

File: vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/java/com/vaadin/flow/component/spreadsheet/Spreadsheet.java [hunk 1]
```diff
@@ -4242,12 +4258,33 @@ private OverlayInfo createOverlayInfo(SheetOverlayWrapper overlayWrapper) {
...
+            info.col = 1;
+            info.row = 1;
+
+            var xssfAnchor = (XSSFClientAnchor) anchor;
+            info.dx = (Long) xssfAnchor.getPosition().getX()
+                    / Units.EMU_PER_PIXEL;
+            info.dy = (Long) xssfAnchor.getPosition().getY()
+                    / Units.EMU_PER_POINT;
+            info.width = xssfAnchor.getSize().getCx() / Units.EMU_PER_PIXEL;
+            info.height = xssfAnchor.getSize().getCy() / Units.EMU_PER_POINT;
```
Comment (tomivirkki) [inline vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/java/com/vaadin/flow/component/spreadsheet/Spreadsheet.java:4277]: `EMU_PER_PIXEL` used for x offset and width, same as [here](https://github.com/vaadin/flow-components/blob/5876423ab1e14d4888ea5f8d800c6bfca5e0d6f1/vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/java/com/vaadin/flow/component/spreadsheet/SheetOverlayWrapper.java#L96)

`EMU_PER_POINT` used for y offset and height, same as [here](https://github.com/vaadin/flow-components/blob/5876423ab1e14d4888ea5f8d800c6bfca5e0d6f1/vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/java/com/vaadin/flow/component/spreadsheet/SheetOverlayWrapper.java#L130)

**Comment by DiegoCardoso** [comment]
I checked the file in Spreadsheet for V8 and Excel and the picture of type 3 are slightly mispositioned.

That's how they look in SS for Flow:
picture_sheet.xlsx in Spreadsheet for Flow

That's how they look in SS for V8:
picture_sheet.xlsx in Spreadsheet for V8

Note that compared with Excel, the pictures are also not correctly positioned even for V8:
picture_sheet.xlsx in Excel

Since this is already an issue with V8, we can try to address it in a separate ticket.

**Comment by tomivirkki** [comment]
> I checked the file in Spreadsheet for V8 and Excel and the picture of type 3 are slightly mispositioned.

Yeah I referred to this issue in https://github.com/vaadin/flow-components/pull/3957/files#diff-98d9f4e55370d300e7bb5421b3b767b378f0372f671db7a7484785f3aaa81a5aR67-R68

**Review by DiegoCardoso — APPROVED** [review]
