### PR TITLE
fix: return the item position of an item in Select if it exists

### LINKED ISSUE #1094: Select getItemPosition always returns -1
Hi,

`getItemPosition()` is not delegated to `InternalListBox` and thus the default implementation from `HasItemsAndComponents` is used which will always return -1 because the items are not children of the Select box.

```
// Actual:
final Select<String> select = new Select<>();
select.setItems("one", "two", "three");
select.getItemPosition("two");   // -1

// Expected to behave like ListBox:
final ListBox<String> listBox = new ListBox<>();
listBox.setItems("one", "two", "three");
listBox.getItemPosition("two");   // 1
```

Tested with 2.1.0 (Vaadin LTS 14.3) but the latest version does not seem to delegate either.

### PR DESCRIPTION
**Pull request by sujoykd**
## Description

`getItemPosition` in `Select` is delegated to the underlying `InternalListBox` field to return the correct item position.

Fixes #1094

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/contributing/overview
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.
- [ ] I have not completed some of the steps above and my pull request can be closed immediately.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

File: vaadin-select-flow-parent/vaadin-select-flow/src/test/java/com/vaadin/flow/component/select/SelectTest.java [hunk 1]
```diff
@@ -887,6 +887,15 @@ public void implementsInputField() {
                 select instanceof InputField<AbstractField.ComponentValueChangeEvent<Select<String>, String>, String>);
     }
 
+    @Test
+    public void getItemPosition_ShouldGetTheActualIndexOftheItemIfItExists() {
```
Comment (vursen) [inline vaadin-select-flow-parent/vaadin-select-flow/src/test/java/com/vaadin/flow/component/select/SelectTest.java:891]:
```suggestion
    public void getItemPosition_returnsIndexIfItemExists() {
```

**Review by vursen — APPROVED** [review]
LGTM. 

I noticed that the issue was originally reported for Vaadin 14. Are we planning to backport this fix there?

File: vaadin-select-flow-parent/vaadin-select-flow/src/test/java/com/vaadin/flow/component/select/SelectTest.java (hunk 1 above)
Comment (sujoykd) [reply vaadin-select-flow-parent/vaadin-select-flow/src/test/java/com/vaadin/flow/component/select/SelectTest.java]: have applied the suggested changes

**Comment by sujoykd** [comment]
>I noticed that the issue was originally reported for Vaadin 14. Are we planning to backport this fix?
@vursen - Not sure what is the protocol here. Sure we could backport this, maybe we can discuss in one of our dailies.
