### PR TITLE
fix: change number formatting with comma as decimal separator

### LINKED ISSUE #5731: Spreadsheet:  Incorrect number formatting in formula - locale and precision is lost
### Description

When you enter a number with lots of digits to the cell, then the actual value of the number is truncated by `CellValueManager.EXCEL_FORMULA_BAR_DECIMAL_FORMAT`. That is very similar behavior as in Excel 2019, where the number is trucated so it has 16 digits (entering `=0,123456789012345678` to a cell in Excel 2019 turns into `=0,123456789012345` in the formula bar).

This behavior works correctly in `Spreadsheet` only when you enter a plain number to a cell (as shown in the first part of the video). Once you enter the number as a formula (with a leading `=`), then strange things start to happen. The value in the cell is displayed correctly, but when you go to the formula bar then:
1. The number is truncated to only three decimal places in the formula bar. So the precision is lost - you cannot edit the original number!
2. Select the cell and go to another sheet, then return back -> suddenly, the number in the formula bar has the original precision, but it's not formatted using the current UI locale!

See it on this video:

https://github.com/vaadin/flow-components/assets/1890879/854963f9-d0ab-4156-bc9a-fb0414a707c8

### Expected outcome

I'd expect numbers, that are part of formulas, to be always formatted using the current UI locale and I'd expect, that the numbers in the formula bar show maximum possible precision - regardless of whether they are part of a formula or not

### Minimal reproducible example

See the behavior on the attached video

### Steps to reproduce

See the behavior on the attached video

### Environment

Vaadin version(s): 24.3
OS: MacOs
Not browser related

### Browsers

_No response_

### PR DESCRIPTION
**Pull request by DiegoCardoso**
## Description

Change the number formatting configuration for locales that use commas as decimal separators. Before, the fraction part of the numbers in such locales would allow only 3 digits. This change allows more digits in the fractional part.

Fixes #5731

## Type of change

- [X] Bugfix
- [ ] Feature

### CODE REVIEW

File: vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/java/com/vaadin/flow/component/spreadsheet/FormulaFormatter.java [hunk 1]
```diff
@@ -280,6 +280,7 @@ protected DecimalFormat getDecimalFormat(Locale locale) {
         DecimalFormat instance = (DecimalFormat) DecimalFormat
                 .getInstance(locale);
         instance.setGroupingUsed(false);
+        instance.setMaximumFractionDigits(15);
```
Comment (vursen) [inline vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/java/com/vaadin/flow/component/spreadsheet/FormulaFormatter.java:283]: If I understand correctly, this setting should match the number of fraction digits specified in `EXCEL_FORMULA_BAR_DECIMAL_FORMAT`. However, that format allows for 16 digits, not 15.

https://github.com/vaadin/flow-components/blob/0a86fa9cfaaf0d4cfd6517ca4489f12537cdae8b/vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/java/com/vaadin/flow/component/spreadsheet/CellValueManager.java#L81

Comment (DiegoCardoso) [reply vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/java/com/vaadin/flow/component/spreadsheet/FormulaFormatter.java]: Good catch. Aligned the number of decimal digits with the one used by the `CellValueManager` class.

**Review by vursen — APPROVED** [review]
