### PR TITLE
fix!: make setValue emulate real user input

### LINKED ISSUE #3420: `setValue` doesn't trigger validation for some TB field elements
### Description

Currently, Field TestBench elements trigger `blur` and `change` on the component's host rather than the input when setting a value with `setValue()`, which results in validation not running.

https://github.com/vaadin/flow-components/blob/39b52fd4eba14cd4838a72eac5b78bc10e96dfd2/vaadin-text-field-flow-parent/vaadin-text-field-testbench/src/main/java/com/vaadin/flow/component/textfield/testbench/TextFieldElement.java#L35-L40

This is apparently an omission from the a11y slotted refactoring.

### Affected components

- TextFieldElement
- TextAreaElement
- EmailFieldElement
- IntegerFieldElement
- NumberFieldElement
- PasswordFieldElement
- BigDecimalFieldElement

### Expected outcome

`setValue()` of Field TextBench elements should trigger `blur` and `change` on the input rather than the host after a new value is set. 

Note, if `change` and `blur` are triggered on the input, then `setValue()` should also trigger an `input` event before the `change` event as otherwise the input's value won't be synced with the field's `value` property.

### Environment

Vaadin version(s): 21, 22, 23
OS: Mac OS

### Browsers

_No response_

### PR DESCRIPTION
**Pull request by vursen**
## Description

This PR changes the `setValue` method for field components to make it emulate real user input firing `input` and `change` DOM events rather than just setting the `value` property on the host element. This is needed to allow using this method for testing validation behavior on invalid user input – the web components trigger validation on `change` DOM event but not all and not always on `value` property change.

Also, see https://github.com/vaadin/flow-components/issues/3420#issuecomment-1190086875 explaining why using `sendKeys` is not an option for `setValue`.

> **Warning**
> It is an altering behavior change.

Fixes #3420 

## Type of change

- [x] Bugfix

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs-beta/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

### CODE REVIEW

File: vaadin-text-field-flow-parent/vaadin-text-field-testbench/src/main/java/com/vaadin/flow/component/textfield/testbench/BigDecimalFieldElement.java [hunk 1]
```diff
@@ -32,11 +32,21 @@
...
     @Override
     public void setValue(String string) {
-        HasStringValueProperty.super.setValue(string);
-        dispatchEvent("change", Collections.singletonMap("bubbles", true));
-        dispatchEvent("blur");
+        TestBenchElement input = $("input").first();
+        input.setProperty("value", string);
+        input.dispatchEvent("input", Collections.singletonMap("bubbles", true));
+        input.dispatchEvent("change",
+                Collections.singletonMap("bubbles", true));
```
Comment (sissbruecker) [inline vaadin-text-field-flow-parent/vaadin-text-field-testbench/src/main/java/com/vaadin/flow/component/textfield/testbench/BigDecimalFieldElement.java:49]: Nit: We could consider extracting this in a static helper that receives the TestBench element. Don't have a strong opinion on this though, the code is rather simple.

Comment (vursen) [reply vaadin-text-field-flow-parent/vaadin-text-field-testbench/src/main/java/com/vaadin/flow/component/textfield/testbench/BigDecimalFieldElement.java:49]: Do you have an idea of possible naming for such a helper class?

Comment (sissbruecker) [reply vaadin-text-field-flow-parent/vaadin-text-field-testbench/src/main/java/com/vaadin/flow/component/textfield/testbench/BigDecimalFieldElement.java:49]: We can make it package-private, so naming isn't super important as it can be changed anytime. I would go with a more general `TextFieldElementHelper`, but your suggestion is fine too.

Comment (vursen) [reply vaadin-text-field-flow-parent/vaadin-text-field-testbench/src/main/java/com/vaadin/flow/component/textfield/testbench/BigDecimalFieldElement.java]: 👍  Done.

**Review by sissbruecker — APPROVED** [review]

**Review by DiegoCardoso — APPROVED** [review]

**Comment by vursen** [comment]
I'm still not 100% sure if it is a good idea to override `setValue` to set the value through the input specifically considering that other elements such as `DatePickerElement` will have `setValue` and `setInputValue` because both make sense for it – one is to set a value in the ISO format, and the other one is to set a value in the final date format.
