### PR TITLE
fix: keep opened state with preserve on refresh

### LINKED ISSUE #3541: [Notification] Exception during browser refresh due to PreserveOnRefresh
### Description

If I use PreserveOnRefresh and show a notification, I receive the following error when I press F5:

```
java.lang.IllegalArgumentException: Trying to detach an element from parent that does not have it.
	at com.vaadin.flow.dom.impl.AbstractNodeStateProvider.removeChild(AbstractNodeStateProvider.java:125)
	at com.vaadin.flow.dom.Node.removeChild(Node.java:377)
	at com.vaadin.flow.dom.Element.removeFromParent(Element.java:515)
	at com.vaadin.flow.component.notification.Notification.removeAutoAdded(Notification.java:222)
	at com.vaadin.flow.component.notification.Notification.lambda$initBaseElementsAndListeners$9b1b5227$1(Notification.java:212)
	at com.vaadin.flow.component.ComponentEventBus.fireEventForListener(ComponentEventBus.java:206)
	at com.vaadin.flow.component.ComponentEventBus.fireEvent(ComponentEventBus.java:195)
	at com.vaadin.flow.component.Component.fireEvent(Component.java:378)
	at com.vaadin.flow.component.ComponentUtil.fireEvent(ComponentUtil.java:401)
	at com.vaadin.flow.component.ComponentUtil.onComponentDetach(ComponentUtil.java:263)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at com.vaadin.flow.internal.nodefeature.ComponentMapping.onDetach(ComponentMapping.java:109)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at com.vaadin.flow.internal.StateNode.forEachFeature(StateNode.java:358)
	at com.vaadin.flow.internal.StateNode.fireDetachListeners(StateNode.java:856)
	at com.vaadin.flow.internal.StateNode.onDetach(StateNode.java:342)
	at com.vaadin.flow.internal.StateNode.setParent(StateNode.java:281)
	at com.vaadin.flow.internal.nodefeature.NodeFeature.detatchPotentialChild(NodeFeature.java:97)
	at com.vaadin.flow.internal.nodefeature.StateNodeNodeList.remove(StateNodeNodeList.java:67)
	at com.vaadin.flow.internal.nodefeature.ElementChildrenList.remove(ElementChildrenList.java:54)
	at com.vaadin.flow.dom.impl.AbstractNodeStateProvider.removeChild(AbstractNodeStateProvider.java:128)
	at com.vaadin.flow.dom.Node.removeChild(Node.java:377)
	at com.vaadin.flow.dom.Element.removeFromTree(Element.java:530)
	at com.vaadin.flow.component.internal.JavaScriptBootstrapUI$JavaScriptUIInternalUpdater.lambda$moveToNewUI$0(JavaScriptBootstrapUI.java:436)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.vaadin.flow.component.internal.JavaScriptBootstrapUI$JavaScriptUIInternalUpdater.moveToNewUI(JavaScriptBootstrapUI.java:435)
	at com.vaadin.flow.component.internal.UIInternals.moveElementsFrom(UIInternals.java:774)
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.lambda$getPreservedChain$5(AbstractNavigationStateRenderer.java:803)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.getPreservedChain(AbstractNavigationStateRenderer.java:802)
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.handle(AbstractNavigationStateRenderer.java:168)
	at 
com.vaadin.flow.component.internal.JavaScriptNavigationStateRenderer.handle(JavaScriptNavigationStateRenderer.java:78)
	at com.vaadin.flow.component.internal.JavaScriptBootstrapUI.handleNavigation(JavaScriptBootstrapUI.java:317)
	at com.vaadin.flow.component.internal.JavaScriptBootstrapUI.renderViewForRoute(JavaScriptBootstrapUI.java:280)
	at com.vaadin.flow.component.internal.JavaScriptBootstrapUI.connectClient(JavaScriptBootstrapUI.java:147)
```

This error did not happen in Vaadin 22 (but there was another problem: after browser refresh, the notification contained another arbitrary component of the page. It seems that there was/is a problem with changing node ids).

### Expected outcome

The browser should refresh normally and the notification should still be visible.

### Minimal reproducible example

```
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.html.Div;
import com.vaadin.flow.component.notification.Notification;
import com.vaadin.flow.router.PreserveOnRefresh;
import com.vaadin.flow.router.Route;

@PreserveOnRefresh
@Route("test_notifications")
public class TestView_Notifications extends Div{

	
	public TestView_Notifications() {
		setSizeFull();
		
		Button btn = new Button("Test");
		btn.addClickListener(e -> {
			onClick();
		});
		add(btn);
	}
	
	public void onClick() {
		Notification.show("Test");
	}
	
}
```

### Steps to reproduce

Go to /test_notifications
Click the button
Press F5

### Environment

Vaadin version(s): 23.1.3
OS: Windows 10

### Browsers

Issue is not browser related

### PR DESCRIPTION
**Pull request by sissbruecker**
## Description

Preserves the opened state of notifications when using `@PreserveOnRefresh`, while also avoiding an exception that occured when an auto-added notification tried to remove itself when it becomes detached during a page reload.

Fixes #3541

## Type of change

- Bugfix

### CODE REVIEW

File: vaadin-notification-flow-parent/vaadin-notification-flow/src/main/java/com/vaadin/flow/component/notification/Notification.java [hunk 1]
```diff
@@ -593,6 +586,24 @@ protected void onAttach(AttachEvent attachEvent) {
...
 
+    @Override
+    protected void onDetach(DetachEvent detachEvent) {
+        super.onDetach(detachEvent);
+        // When reloading a page using preserve on refresh, the notification
+        // should keep its opened state. To prevent it from auto-closing, delay
+        // the auto-closing logic to before client response, which is not called
+        // when reloading the page. This also prevents an exception when trying
+        // to remove an auto-added notification from its parent.
+        detachEvent.getUI().beforeClientResponse(this, executionContext -> {
```
Comment (sissbruecker) [inline vaadin-notification-flow-parent/vaadin-notification-flow/src/main/java/com/vaadin/flow/component/notification/Notification.java:597]: From my testing it seems this is enough to prevent the error reported in the linked issue, as the before client response is never called when reloading the page. I assume that's because the reload creates a new UI, and there never is a response for the old one that triggered the reload / detach.

This also ensures that the notification keeps its opened state, as the logic for auto-closing below is not executed.
