### PR TITLE
fix: avoid OS limitations on CLI argument length when exporting charts

### LINKED ISSUE #2835: vaadin-charts-flow-svg-generator fails on large charts
### Description

When exporting a 'large' chart (i.e., with a large chart config file) using the `vaadin-charts-flow-svg-generator`, I get an OS error related to the length of a command line argument passed to node

```
Caused by: java.io.IOException: Cannot run program "/opt/rh/rh-nodejs14/root/usr/bin/node": error=7, Argument list too long
at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
at com.vaadin.flow.component.charts.export.NodeRunner.runJavascript(NodeRunner.java:41)
at com.vaadin.flow.component.charts.export.SVGGenerator.generate(SVGGenerator.java:171)
at com.futrix.maverick.staticexport.translation.translators.chart.ChartTranslator.createSvgChart(ChartTranslator.java:157)
... 50 common frames omitted
Suppressed: java.nio.file.DirectoryNotEmptyException: /var/opt/rh/jws5/cache/tomcat/temp/svg-export2060569917357076214
at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:242)
at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:108)
at java.nio.file.Files.deleteIfExists(Files.java:1165)
at com.vaadin.flow.component.charts.export.SVGGenerator.close(SVGGenerator.java:106)
at com.futrix.maverick.staticexport.translation.translators.chart.ChartTranslator.createSvgChart(ChartTranslator.java:158)
... 50 common frames omitted
Caused by: java.io.IOException: error=7, Argument list too long
at java.lang.UNIXProcess.forkAndExec(Native Method)
at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
at java.lang.ProcessImpl.start(ProcessImpl.java:134)
at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
... 53 common frames omitted
```

### Expected outcome

Production of SVG for a beautiful chart.

### Actual outcome

Crash and no chart.

### Minimal reproducible example

Problem is related to the length of the Highcharts config object. Can create a concrete example if needed.

### Steps to reproduce

Clear steps describing how to reproduce the issue.

1. Create, e.g., a line chart with 'lots' of data points
2. Try to export it using the SVGGenerator

### Environment

- `vaadin-charts-flow-svg-generator` 21.0.2 (used with Vaadin 14 core)
- RHEL Linux

### Browsers Affected

N/A - server-side chart export

### PR DESCRIPTION
**Pull request by aroneous**
## Description

fix: Avoid OS limitations on command-line argument length when exporting charts

At least in certain OS environments, server-side export of charts with large config objects fails due to the length of the config object being passed to node on the command line.

Write the chart config object to a temp file and pass its path to the exporter, rather than passing the full config on the command line.

Avoids OS-level limitations on argument length that can prohibit export of large charts.

Still support chart config on the command line, mostly to appease mocha tests.

Fixes #2835

## Type of change

- [x] Bugfix

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs-beta/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

### CODE REVIEW

File: vaadin-charts-flow-parent/vaadin-charts-flow-svg-generator/jsdom-exporter.js [hunk 1]
```diff
@@ -191,14 +193,24 @@ const inflateFunctions = (jsonConfiguration) => {
...
  * @param {ExportConfiguration} configuration
  *
  * @returns {Promise<SVGResult>} Object with the result of the export
  */
-const jsdomExporter = ({ chartConfiguration, outFile = 'chart.svg', exportOptions }) => {
+const jsdomExporter = ({ chartConfigurationFile, chartConfiguration, outFile = 'chart.svg', exportOptions }) => {
     return new Promise((resolve, reject) => {
+        if (chartConfigurationFile) {
+            chartConfiguration = JSON.parse(
+                fs.readFileSync(path.join(__dirname, chartConfigurationFile)).toString()
```
Comment (sissbruecker) [inline vaadin-charts-flow-parent/vaadin-charts-flow-svg-generator/jsdom-exporter.js:211]:
```suggestion
                fs.readFileSync(path.join(__dirname, chartConfigurationFile), 'utf8').toString()
```
One concern about `fs.readFileSync` is the text encoding to be used for converting the byte data into a string. I can't see any clear information in the node.js docs which encoding it will use if you don't explicitely specify one, I guess it might be the system default. This can lead to broken characters if you provide a UTF-8 encoded file, and read it on a system that uses a different encoding. Since we [explicitely save the file using UTF-8 encoding](https://github.com/vaadin/flow-components/pull/2836/files?diff=unified&w=0#diff-ba2c17cca75426fd099e91330f1467becd8c210d950b189d040786ed5193646cR174-R175), I think we can also explicitely read it as UTF-8.

Comment (vursen) [reply vaadin-charts-flow-parent/vaadin-charts-flow-svg-generator/jsdom-exporter.js:211]: Good point, applied.

**Review by vursen — APPROVED** [review]
